### ISSUE TITLE
[Deployment Issue] Node ID is not replaced correctly if left blank

### ISSUE THREAD

**Issue by cattoshi** [caprover/caprover#573] opened 2019-12-29 14:47 UTC
**What is the problem?**

Caprover replaces a blank Node ID (on the 'App configs' tab) with an obsolete one, for example a Node ID of an already removed node that is no longer part of the swarm.

**Steps to reproduce the problem:**

Manually change Node ID app configuration from the gui, leave it blank. Click the 'Save and Update' button. An obsolete id is placed but the process completes. Click again on 'Save and Update', the process fails with `1000 : Node ID you requested in not part of the swarm <NODE_ID>`.

Answers to the following questions if applicable:
- Your OS and version? Ubuntu 18.04
- Docker version: 19.03.1
- Caprover version: 1.6.0

**Comment by githubsaturn** [comment] 2019-12-29 16:21
I don't understand the steps to reproduce. Does the original node id was the one that got removed?

**Comment by cattoshi** [comment] 2019-12-29 18:53
I'll explain better, I made some tests:

1. Spin up a digitalocean worker, make it join the swarm as worker through gui.

2. Create a service through the gui
3. Change Node ID for that service to the new worker id
4. Make the worker leave the swarm
5. In Caprover GUI edit again the node id and leave it blank and click save. It should be replaced automatically as the tooltip says.
6. The blank Node ID is replaced with the old worker node id. Making the service to be placed nowhere.
7. Go to docker manager console and remove the worker node that just departed the swarm with `docker node rm <nodeid>`.
8. Go to caprover gui and replace the Node Id for our service with a blank node id again. and click save. Again the old worker obsolete id that departed the swarm and got removed manually is placed. Again the saving process succeeds, but service is not placed anywhere (0 replicas).
9. Click again the save button, error message shows: `Node ID you requested in not part of the swarm`

The problem is that Caprover is filling the blank node id field with a value that will create an error later.

**Comment by cattoshi** [comment] 2019-12-29 18:57
It should be replaced with manager node id so the manager can take care of resources imo. If the user leaves blank it should be interpreted as the user leaving it to the manager for placement. But instead it uses a fixed node id (that could potentially have been removed, causing error).

**Comment by cattoshi** [comment] 2019-12-29 19:18
There's also a typo in the error message.

**Comment by githubsaturn** [comment] 2019-12-29 21:15
I see where the confusion is coming from. This is actually the intended behavior, but the problem is that it’s not communicated to the user properly. When you enter a blank Node ID, CapRover sets the NodeID only it has never been set before. This is just for the very first initialization. When you first create a persistent service, Docker Swarm places the service on a node based on the current load of each node. On the first update, CapRover “glues” the service to the node that Docker Swarm created in order to ensure that the persistent data won’t get lost. After this point, even if you use an empty NodeID, CapRover/Docker won’t “automatically” change the NodeID - because the service is glued to that particular NodeID.

If you want to change the NodeID, you’ll have to explicitly change the NodeID.



——


Regarding the typo - I’ll fix it 👍

**Comment by githubsaturn** [comment] 2019-12-29 21:19
Typo fixed in 28c992bf46f784f78be2ccd54c916e0f8c7b4aa3

**Closed by githubsaturn** 2019-12-29 21:19 UTC
Labels: deployment-issue

**Comment by cattoshi** [comment] 2019-12-29 21:46
Understood, thanks.

**Comment by hhieubeehexa** [comment] 2024-05-28 12:45
I revert the app config from config-captain.json.backup. And got this issue 

- 1000 : Node ID you requested is not part of the swarm cluster: 9tpei7cykmjgyhr0vi6o3tvps

**Comment by githubsaturn** [comment] 2024-05-28 15:51
Pause CapRover, the edit the config file and remove 
9tpei7cykmjgyhr0vi603tvps. Just leave an empty string. Reload CapRover

**Comment by hhieubeehexa** [comment] 2024-05-28 15:52
> Pause CapRover, the edit the config file and remove 9tpei7cykmjgyhr0vi603tvps. Just leave an empty string. Reload CapRover

I tried, but no hope :(

**Comment by githubsaturn** [comment] 2024-05-28 16:01
Do you still have the buggy node id in the config?

**Comment by mirite** [comment] 2024-09-13 13:07
I was having the same problem after needing to reinstall Caprover. The original node id gets filled in instead of the new one when left blank. You can grab the correct new node id from the Cluster screen
