### ISSUE TITLE
post deployment hooks

### ISSUE THREAD

**Issue by john-dev** [caprover/caprover#816] opened 2020-08-31 06:24 UTC
**Describe the solution you'd like**
It would be nice to execute post-deployment apps or commands.

**Describe alternatives you've considered**
Adding a webhook from each service's git repo to the app holding all our tests (requires us to add an unknown delay)

**Additional context**
We have a microservice architecture and it fits just nice with capraover, but as 14 app's rely on each other, it would be nice to run our integration tests whenever you re-deployed one of the app's (maybe with a delay)

**Comment by githubsaturn** [comment] 2020-08-31 12:00
Duplicate of https://github.com/caprover/caprover/issues/727

**Closed by githubsaturn** 2020-08-31 12:00 UTC
