### ISSUE TITLE
Using Caprover with custom SSL certificates

### ISSUE THREAD

**Issue by yasin-eraslan** [caprover/caprover#1247] opened 2021-11-03 13:31 UTC
### Discussed in https://github.com/caprover/caprover/discussions/1246

<div type='discussions-op-text'>

<sup>Originally posted by **yasin-eraslan** November  3, 2021</sup>
So I will use Caprover for my Bachelor Thesis any my first problem is using custom SSL certificates.

I am not allowed to use the Lets Encrypt certificates and has to use custom ones, What I did was moving my certs to /captain/data/nginx-shared and referenced them like it is told in the docs.

I edited my settings in the caprover dashboard to this:

Default catch-all page. e.g. if you enter SOME-RANDOM-CHARS.captainroot.domain.com
   ```
 server {
      # Catch all HTTP
        listen       80;

        # Catch all HTTPS
        listen              443 ssl;
        ssl_certificate     /nginx-shared/apps_mni_thm_de.pem;
        ssl_certificate_key /nginx-shared/caprover.mni.thm.de.key 

```

After I save this and let him reload , everything breaks, what am I doing wrong or what am I missing ?
Or am I configuring it on the wrong place?</div>

**Comment by githubsaturn** [comment] 2021-11-03 13:55
Duplicate of https://github.com/caprover/caprover/discussions/1246

**Closed by githubsaturn** 2021-11-03 13:55 UTC
