### ISSUE TITLE
schemaVersion for CapRover

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#361] opened 2019-02-03 10:03 UTC
According to [the docs](https://caprover.com/docs/captain-definition-file.html) (and this is also mentioned in the announcement of caprover), the captain-definition file should set `schemaVersion` to `2` rather than `1`.

OK this is not a big deal, but to ease migration for users and for backward compatibility, couldn't/shouldn't caprover understand `schemaVersion: 1` as well?  This would allow existing `captain-definition` files to work without modification... yes a warning could be issued to suggest that the file be updated to be in line with the new schema, but at least it eases the upgrade process for the user.  I'd rather leave my `captain-definition` files alone completely until I know that caprover is working OK and that I can leave captainduckduck behind... I don't like the idea of making changes that I might have to reverse if something doesn't work as expected in the migration process.

At present, if the `schemaVersion` is set to `1` it just gives up... but to me it seems that it would not be too difficult for caprover to understand and handle both, at least for a transition period... the changes do not seem to be that major that caprover could not interpret both.  (And if the soon-to-be-announced migration script can make these changes automatically, this means that the same logic could be integrated into the `captain-definition` file parser itself.)

**Comment by githubsaturn** [comment] 2019-02-04 17:38
Some notes:
- I plan to release migration script by tomorrow.
- This is a one-time and one-way change. It's a breaking API change.
- Supporting schemaVersion 1 is not impossible, but it's not as simple as what it looks - due to the redesigned image making flow.
- You shouldn't have any concern regarding stability of CapRover. It uses the same underlying tech stack. The code engine is the same with added statically typed typescript.  So if anything, it's more stable than CaptainDuckDuck. I am personally committed to fixing regression bugs in <24hr.

Last, but not least:
- To be honest, I think you, and other users, will benefit more from me spending my time building new features rather than spending time adding support for old schema which may be used once or twice and that's it. Like I said, this is not a 1hr task, it touches so many components in the flow.

Hope it answers your question.

**Closed by githubsaturn** 2019-02-04 17:38 UTC
Labels: question
