### ISSUE TITLE
Duplicate app

### ISSUE THREAD

**Issue by hadikcz** [caprover/caprover#980] opened 2021-01-20 21:14 UTC
Button in app list for duplicate that app will be great. Because sometime I want deploy another branch but everything is same (env, creds etc). Of course cli is the way, but this is request feature for webui.

**Comment by githubsaturn** [comment] 2021-01-20 23:41
Duplicate of this: https://github.com/caprover/caprover/issues/796

**Closed by githubsaturn** 2021-01-20 23:41 UTC
