### ISSUE TITLE
[Deployment Issue] Deployment via github suddenly fails "Host key verification failed."

### ISSUE THREAD

**Issue by pixply** [caprover/caprover#1265] opened 2021-11-17 11:21 UTC
Deployments via github and webhook worked fine the whole time.

I haven't changed anything on the repository or the server, but suddenly deployments via webhook or manually (Force Build) end in: 

```
Build started for appname
Build has failed!
----------------------
Deploy failed!
Error: Cloning into '/captain/temp/image_raw/appname/32/source_files'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

The keys are correct. I even created a new one to test and it doesnt work either. 

If i try it manually from the captains shell, the key works

```
ssh -i devdeploykey -T git@github.com
Hi GithubUser/appname! You've successfully authenticated, but GitHub does not provide shell access.
```

Any advice where to look for more details about the error?

**Comment by natemking** [comment] 2021-11-17 13:21
@pixply Do the update to 1.10.1. It fixed my servers.

**Comment by cancng** [comment] 2021-11-17 13:48
> @pixply Do the update to 1.10.1. It fixed my servers.

I already use 1.10.1 update but same error. 

```
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Chaisser** [comment] 2021-11-17 14:04
Issue still exists at 1.10.1 (latest version). And it appears suddenly wihout touching any configuration. 

I create another key, I logged in use ssh agent add key and everything. It still not working.

**Comment by aaron5670** [comment] 2021-11-17 15:10
Same issue here...

**Comment by githubsaturn** [comment] 2021-11-17 15:20
Is everyone here using Github? Does the issue appear on any other platforms?

Trying to sort out what happened here all of a sudden without any code changes.

**Comment by pixply** [comment] 2021-11-17 15:22
I'm solely using GitHub. Don't have any other repository provider to check.

**Comment by aaron5670** [comment] 2021-11-17 15:26
Fixed by rebooting my VPS

**Comment by pixply** [comment] 2021-11-17 19:59
I can confirm, rebooting did it... But still would like to know the cause... rebooting in production is not always a good option.

**Comment by githubsaturn** [comment] 2021-11-18 00:13
I just tried it and I cannot reproduce it. Consider that:
- Lots of people started seeing this all of a sudden at once
- And, everyone here seems to see the issue happening on Github
- And, that there were no code changes,
I am assuming this was a Github issue where for some reason, they may have sent out wrong SSH certs back to the clients for a short period of time. 


Next time this happens, please do not reboot. First try just restarting the container:
```
docker service update --force captain-captain
```

**Comment by hamza-younas94** [comment] 2021-11-18 20:13
i am also facing the same issue

**Comment by githubsaturn** [comment] 2021-11-18 20:40
When did it start? Can you run the command that I have above. Does it fix it?

**Comment by moellrich** [comment] 2021-11-18 22:29
Hi, since yesterday I had from time to time the same issue. Bad I found this page not earlier.
@githubsaturn : Your command fixed it. (Well, the first container is deploying now. Hope the other ones will do as well).

Question I wrote also on Slack: I logged into the captain container and removed via "ssh-keygen -R github.com" over 150 lines. I guess that are roundabout 149 too much, or am I wrong?

**Comment by bakdakonusuruz** [comment] 2021-11-18 23:13
Hi all, I start having this issue just today.
I did @githubsaturn 's suggestion and didn't help, then I tried to restart the server and now having another problem.

`Build has failed!
----------------------
Deploy failed!
Error: Cloning into '/captain/temp/image_raw/teco-service-api/22/source_files'...
Warning: Permanently added the ECDSA host key for IP address '140.82.121.4' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

**Comment by githubsaturn** [comment] 2021-11-18 23:41
If anyone is using any service other than GitHub please let me know. This issue seems to be isolated to GitHub. 

Looks like that they recently started depreciating some legacy host keys and that's probably what caused this.

https://github.blog/2021-09-01-improving-git-protocol-security-github/#when-are-these-changes-effective

I'll continue to look for a solution, but unfortunately I haven't been able to reproduce so far.

**Comment by bakdakonusuruz** [comment] 2021-11-18 23:42
> If anyone is using any service other than GitHub please let me know. This issue seems to be isolated to GitHub.
> 
> Looks like that they recently started depreciating some legacy host keys and that's probably what caused this.
> 
> https://github.blog/2021-09-01-improving-git-protocol-security-github/#when-are-these-changes-effective
> 
> I'll continue to look for a solution, but unfortunately I haven't been able to reproduce so far.

Hi there @githubsaturn ,
I updated my SSH keys to the new ones and worked well.

FYI.

**Comment by githubsaturn** [comment] 2021-11-19 01:45
Thanks for confirming this. 

# 🚨🚨 READ THIS:

This is a [Github specific issue](https://github.blog/2021-09-01-improving-git-protocol-security-github/#when-are-these-changes-effective), it's unrelated to CapRover. To fix:
* Make sure you create keys that are compatible with [Github's new requirements](https://github.blog/2021-09-01-improving-git-protocol-security-github/#when-are-these-changes-effective)
* Run `docker service update --force captain-captain` to remove all the previous keyscan results.

To create a key pair that works with Github, simply run this:
```bash
ssh-keygen -t ed25519 -C "yourname@example.com" -f ./deploykey -q -N ""
```

This command will create a `deploykey` and `deploykey.pub` in your current directory. You need to copy the private key into CapRover and the public key to Github. And you're good to go.

**Comment by cpecorari** [comment] 2021-11-20 09:56
Hi, also having the issue, but unable to go past this event with trying every answer...

Caprover 1.10.1, 15 apps, few with GitHub SSH key, others one-click apps, on a VPS server `Ubuntu 18.04.6 LTS` & `Docker version 20.10.11, build dea9396`

Initially with PEM key, stopped functioning with `Host key verification failed.`

Coming here, updating keys with `ssh-keygen -t ed25519 -C "yourname@example.com" -f ./deploykey -q -N ""` on GitHub repo  & cap rover app, saving, then `docker service update --force captain-captain` and now having : 
```
------------------------- Sat Nov 20 2021 09:00:24 GMT+0000 (Coordinated Universal Time)
Build started for xyz-prod
Build has failed!
----------------------
Deploy failed!
Error: Cloning into '/captain/temp/image_raw/copytrading-prod/15/source_files'...
Warning: Permanently added the ECDSA host key for IP address '140.82.121.3' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Tried restarting the server, updating app, creating new key, like 10 different times & options, still the same issue.
If you could point me to any direction... Much appreciated !
Thanks

**Comment by moellrich** [comment] 2021-11-20 11:51
@cpecorari: My containers are building now. The last thing I did was to restart caprover with "docker service update --force captain-captain".
But one thing I did sometimes before was to logon to the server and ran "ssh-keygen -R github.com". I am not sure if this had a relevant impact. Maybe you can give it a try.

**Comment by githubsaturn** [comment] 2021-11-20 15:13
This is all that's happening on CapRover under the hood:
https://github.com/caprover/caprover/blob/6fdcb8b1e4aa4e2acafb02ec5914b3e9bfba4c4e/src/utils/GitHelper.ts#L61-L91


If your keys work, there is no reason for CapRover not to work. Can you create a test repository with test private and public key and comment them here? (test repo link, test private key, test public key)

**Comment by cpecorari** [comment] 2021-11-20 17:35
What the... Thanks a lot @githubsaturn **it was the empty new line at the end**... on a `cat key` command it won't copy the new line !
What a lesson learned on like 6 hours for an empty line...

**Closed** 2021-11-28 21:09 UTC
Labels: deployment-issue

**Comment by Aeolun** [comment] 2022-04-19 14:16
As silly as this is, is it possible for caprover to add it's own newline in case it doesn't exist at the end of the specified key? That'll save a ton of people from running into this same issue.
