### ISSUE TITLE
[Deployment Issue] One Click Apps

### ISSUE THREAD

**Issue by derkweijers** [caprover/caprover#481] opened 2019-08-15 11:20 UTC
**IMPORTANT:** Please avoid posting issues that are not specific to CapRover. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

--------------------------------------------------------------------------

What is the problem?
one-click apps fail to deploy on the new 1.5.1. It fails during the configure stage.

If applicable, content of `captain-definition` file:
Every one-click deploy app.

Steps to reproduce the problem:
Deploy a one-click app. Tested on 2 machines (existing one and a new one) with the same result.

Answers to the following questions if applicable:
- Your OS and version: Ubuntu 18.04.3
- RAM? 4

**Comment by githubsaturn** [comment] 2019-08-15 12:56
Hi Derek, thanks for reporting this.

- What is the version of CapRover you're using? You can see the version in settings page.
- What is the browser you're using?
- Which the one-click app you're experiencing the problem with.

I've just tested adminer one-click app on CapRover 1.5.1 using Chrome, and things went well and the app was deployed.

**Comment by derkweijers** [comment] 2019-08-15 13:00
- What is the version of CapRover you're using? You can see the version in settings page.
The newest available, 1.5.1
- What is the browser you're using?
Brave, Chrome and Safari
- Which the one-click app you're experiencing the problem with.
All of them

It fails with: Failed: Error: Build in-progress for test. Please wait...
I've also tried to restart the server but I still get this error.

**Comment by githubsaturn** [comment] 2019-08-15 13:06
Thanks for the info. This may be an actual bug. Will look into this asap.

**Comment by githubsaturn** [comment] 2019-08-15 13:07
Is "test" the name of the one-click app that you're trying to deploy?

**Comment by githubsaturn** [comment] 2019-08-15 13:43
@derkweijers 

Can you please update your version to the edge version and confirm if the issue is resolved? Once you confirm the fix, I'll deploy a hotfix.

Switch to edge:
https://caprover.com/docs/troubleshooting.html#how-to-use-the-edge-version

MAKE SURE to force refresh your browser after updating to the version.

**Comment by derkweijers** [comment] 2019-08-15 14:05
Confirmed! Thanks 👍

**Comment by githubsaturn** [comment] 2019-08-15 14:12
Thanks!

Fixed in 1.5.2

**Closed by githubsaturn** 2019-08-15 14:12 UTC
Labels: bug, deployment-issue
