### ISSUE TITLE
Group applications in UI

### ISSUE THREAD

**Issue by Satont** [caprover/caprover#1141] opened 2021-07-03 12:57 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i need spend time to actually search each application grouped in mi mind. Like i has app1 + app1-db + app1-redis, and it always requires search by name for me. Grouping will solve much issues and will looks much cleaner.

**Describe the solution you'd like**
Click to expand/hide.

**Describe alternatives you've considered**
Not really.

**Additional context**
Well i has like 50+ apps, and it annoying to search them.

**Comment by githubsaturn** [comment] 2021-07-03 16:54
Duplicate of https://github.com/caprover/caprover-frontend/issues/52

**Closed by githubsaturn** 2021-07-03 16:54 UTC

**Comment by Satont** [comment] 2021-07-03 17:15
Sorry, didnt notice there is front repo.
