### ISSUE TITLE
[FEATURE] Bulk edit apps in list view

### ISSUE THREAD

**Issue by JonathanDoelan** [caprover/caprover#1615] opened 2022-12-22 13:37 UTC
Would be nice to have the ability to delete multiple apps at the same time.
Maybe by checking a checkbox close to the app name in the list view. If a checkbox is clicked, a button appears to delete the selected apps.

**Comment by githubsaturn** [comment] 2022-12-23 04:36
Dupe of https://github.com/caprover/caprover-frontend/issues/46

**Closed by githubsaturn** 2022-12-23 04:36 UTC
