### ISSUE TITLE
Manage httpauth from the UI

### ISSUE THREAD

**Issue by derek-adair** [caprover/caprover#357] opened 2019-01-31 14:31 UTC
I would like to use caprover for easily staging demos that are private.

It'd be super slick...

**Comment by githubsaturn** [comment] 2019-01-31 16:17
Dupe of https://github.com/caprover/caprover/issues/336

**Closed by githubsaturn** 2019-01-31 16:17 UTC

**Comment by derek-adair** [comment] 2019-02-07 15:30
oh wow thats a way better submission. i  feel shame.
