### ISSUE TITLE
[Feature Request] Add domain alias

### ISSUE THREAD

**Issue by etienne-dldc** [caprover/caprover#314] opened 2018-11-06 13:19 UTC
Hi 👋 

I would like to be able to add a new domain on an app as an alias that would redirect to the main domain.

Example: 

- I have an app on `myapp.captain.myserver.com` 
- I add a domain `myapp.com`
- I add an alias `www.myapp.com` (this redirect www.myapp.com to myapp.com with a 302)

**Comment by githubsaturn** [comment] 2018-11-07 00:36
It is already possible. You can do this in multiple ways:
1) You can add as many "custom" domains as you want to your app. i.e., you can have `myapp.com` `www.myapp.com` and anything else, all resolving to your `myapp.captain.myserver.com`
2) if you want a redirect for sure, you can do this in two ways:
2a) Do it at the application level. e.g., in ExpressJS, `res.redirect('myapp.com');`
2b) Create a dummy app, connect  `www.myapp.com` and redirect in nginx level to `myapp.com`. You don't even need to deploy anything.

**Comment by etienne-dldc** [comment] 2018-11-07 10:01
My point was that it would be nice to have that without having to either set it up at the application level or having a dummy app with custom nginx config...

**Comment by githubsaturn** [comment] 2018-11-08 07:31
I see. I'll reopen this for now. But I am not sure how value this adds, considering that it's already possible, only with some nginx modifications. Anyways, we'll leave it open for now will decide later.

**Comment by tuefekci** [comment] 2018-12-10 20:03
Should it not be enought to setup an One-Click App which takes an env var for the redirect is kinda stupid but way simpler then adding dynamic redirects to the routing layer, which would be nice but is probaly hard?

**Comment by tuefekci** [comment] 2018-12-14 01:20
So i thought a bit more about it and its works atleast in my setup perfectly via nginx configuration in the web interface you can add it to your projects or the global configuration depending on your usecase.

`server {
	listen 80;
	listen [::]:80;

	server_name www.myapp.com;

	return 301 http://myapp.com$request_uri;
}`

**Comment by mmoyano16** [comment] 2019-02-21 03:14
Hi! i have a question. I was created a new domain for one of my apps.

newdomain.tk

But, when i create a CNAME alias which redirect to myapp.captaindomain.tk, the browser URL don't stay the same, it changes to "myapp.captaindomain.tk" again.

Is there any way to achieve this redirection without changing the browser URL? 

thnks!

**Comment by githubsaturn** [comment] 2019-02-21 04:15
Don't use CNAME redirection. Use A record:
- Set `newdomain.tk` pointing to `xxx.xxx.xxx.xxx` (your server IP)
- Login to CapRover web dashboard and "Connect New Domain" with `newdomain.tk`
- Now go to browser `newdomain.tk`, this should not redirect. 


Let me know if you are still having issues.

**Comment by natsumi** [comment] 2019-05-30 07:37
@tuefekci have you been able to get that working with force https on?  I can't seem to get it working even with changing it to this
```
server {
	listen 443;
	listen [::]:443;

	server_name www.myapp.com;
	return 301 https://myapp.com$request_uri;
}
```

**Comment by iznotek** [comment] 2019-11-18 22:18
hye everyone, thanks a lot for this so good and easy to use caprover project... but, hehe, i got the same pb as describe and this:

> Don't use CNAME redirection. Use A record:
> Set newdomain.tk pointing to xxx.xxx.xxx.xxx (your server IP)
> Login to CapRover web dashboard and "Connect New Domain" with newdomain.tk
> Now go to browser newdomain.tk, this should not redirect.

does not work at all,  i get the domain arkela.life redirecting... i'm sad...
all is using https... it's just a wordpress auto install with last caprover version on a vps...
any ideas...

**Comment by iznotek** [comment] 2019-11-18 22:30
also if www.arkela.life is set on the adress bar, it fully failed with blue screen "Nothing here yet :/"
with www.arkela.life same A record as arkela.life on ip server... ?

**Comment by valatonload** [comment] 2020-01-28 11:10
Hi folks, one more voice here to voice the fact that the connect a domain feature isn't behaving as intended.

You can get myotherdomain.com to be an alias of to app.cpt.domain.com but ultimately, you'll always be redirected to app.cpt.domain.com
That sorts of defeat the purpose of the alias.

**Comment by s-kris** [comment] 2020-03-19 06:31
An option to set preferred domain for an app will be extremely helpful.

**Comment by funkhauscreative** [comment] 2020-05-20 10:51
Can someone please post a working redirect with ssl enabled? I tried a lot of server combinations in the NGINX config of the app, but still no luck. 

I just want the www.domain.com to redirect to domain.com.

**Comment by sdzyba** [comment] 2020-08-26 21:24
@natsumi 
@funkhauscreative 

try this
```
server {
  listen 80;
  listen 443;
  server_name www.<%-s.publicDomain%>;
  return 301 $scheme://<%-s.publicDomain%>$request_uri;
}
```

`<%-s.publicDomain%>` is replaced by CapRover with the domain name, but you may just replace the value by yourself with `myapp.com`

**Comment by IMarty** [comment] 2020-11-06 14:44
That still not work :/
What could be a better nginx.conf for the root setting in order to have my server responding with the good app ? 
I have an app "my-wordpress.igor-marty.fr" that is working fine with https !
I own a domaine "my-wordpress-example.fr"
I have set the DNS to point to the server
But right now, when I visite the url I get a message "Nothing here yet :/ "
How can I make  : 

1. "my-wordpress-example.fr" shows the app my-wordpress.
2.  have "igor-marty.fr" shows a specific website.

**Comment by githubsaturn** [comment] 2020-11-06 22:35
Go to your apps > wordpress > Connect a new domain

You can see it in action in the demo website under "demo-nodejs"
https://captain.server.demo.caprover.com


![image](https://user-images.githubusercontent.com/10582082/98420980-59c08e80-2056-11eb-918f-bd95305552a6.png)


PS: this is unrelated to this thread, for further questions please open a new issue.

**Comment by githubsaturn** [comment] 2023-05-09 05:06
Done. It'll be part of the next release:

![image](https://user-images.githubusercontent.com/10582082/236999008-e4990cc7-939b-4653-ba92-b0cec24379cc.png)

**Closed by githubsaturn** 2023-05-09 05:06 UTC
Labels: feature-request
