### ISSUE TITLE
Failed: Error: Push failed: Error: (HTTP code 500) server error - invalid reference format 

### ISSUE THREAD

**Issue by marhaupe** [caprover/caprover#434] opened 2019-05-20 17:36 UTC
I set up my CapRover installation with the DigitalOcean droplet. I followed the setup instructions and wanted to deploy a test application. Deploying any One-Click-App, as well as deploying a new custom app, results in the following error:

```
1000 : Push failed: Error: (HTTP code 500) server error - invalid reference format
```

It seems like this is a bug.

**Comment by githubsaturn** [comment] 2019-05-20 18:07
Have you setup a push registry on the cluster tab? Docker has recently blocked the double hyphens (--) and it fails during pushing images. Is this the case?

**Comment by marhaupe** [comment] 2019-05-20 19:15
Yes I added a registry. Should I disable it?

**Comment by githubsaturn** [comment] 2019-05-20 19:20
No, it's a problem with some recent changes that Docker has made. Unfortunately, they are now disallowing double hyphens in image names. We'll be changing this pattern to fix the issue with Docker image registry.

**Comment by marhaupe** [comment] 2019-05-20 19:24
Alright at least regular pulling from the registry works. Thanks for the quick help!

**Comment by khromov** [comment] 2020-01-24 02:06
Still having this issue (same error as original poster), is it not fixed in 1.6.1?

**Comment by eugali** [comment] 2020-11-22 14:59
I am having the same issue, but my Docker image has no double hyphens and I would like to keep the docker image registry. 

These are the last lines: 

Successfully built xxxx
Successfully tagged img-captain-xxxx:latest
Build has failed!
----------------------
Deploy failed!
Error: Push failed: Error: (HTTP code 500) server error - invalid reference format

Something bad happened. Cannot deploy xxxx at xxxx-production-01.

Successfully deployed

What could I do?

**Comment by githubsaturn** [comment] 2020-11-22 15:07
Are you using CapRover's built in Docker registry or a 3rd party registry?

**Comment by eugali** [comment] 2020-11-22 15:08
AWS Docker Registry

**Comment by githubsaturn** [comment] 2020-11-22 15:12
You're not using the correct namespace format. 

The correct image name:
For Docker Hub it is `domain.com / username / imagename`
For some registries is `domain.com / username / projectname / imagename`
For some registries is `domain.com / projectname / imagename`

So depending on what the format is you need to change your imagePrefix when setting up your Docker Registry:
![image](https://user-images.githubusercontent.com/10582082/99907519-282d0180-2cab-11eb-83f3-fe4a43c80b40.png)

If you are not sure what format to use, read AWS docs and contact AWS support to understand what format they want your image needs to be.

**Comment by eugali** [comment] 2020-11-22 15:28
There's no Image Prefix at the moment. The repository name is an alphanumeric string. -> amazonaws.com/xxxx

Should I change the name of the repository to include the Image Prefix?

**Comment by githubsaturn** [comment] 2020-11-22 15:31
Can you manually push images to AWS using `docker push` ? If so, what is an example of your image full name?

**Comment by eugali** [comment] 2020-11-22 15:40
This is an example of an image full name: "thisismyimage"

The was domain as a subdomain that is specific for me, hence it does not use any Image Prefix to identify the user

**Comment by eugali** [comment] 2020-11-22 15:41
This is a valid push command: 

docker push 123456789.dkr.ecr.eu-west-1.amazonaws.com/thisismyimage:latest

**Comment by githubsaturn** [comment] 2020-11-22 15:43
Then use
- `123456789.dkr.ecr.eu-west-1.amazonaws.com` as your domain for registry
- Leave image prefix empty

If it doesn't work, try:
- Manually push the image with the exact name that CapRover is trying to push to your aws registry, does it work?
- Take a screenshot of your registry EDIT box in CapRover and paste it here.

**Comment by eugali** [comment] 2020-11-22 15:50
The first attempt didn't work. I then tried to leave the domain "---amazonaws.com" and set the Image Prefix to "myimagename". 

Now I got the following error: 

This might take a few minutes...
{"message":"denied: Your authorization token has expired. Reauthenticate and try again."}
denied: Your authorization token has expired. Reauthenticate and try again.
Push failed...
Build has failed!
----------------------
Deploy failed!
Error: Push failed:
{"message":"denied: Your authorization token has expired. Reauthenticate and try again."}denied: Your authorization token has expired. Reauthenticate and try again.

**Comment by eugali** [comment] 2020-11-22 16:26
Just pushed manually and successfully with the following commands: 

aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 123123123.dkr.ecr.eu-west-1.amazonaws.com

docker build -t my image .

docker tag wingleproductionwebserver:latest 123123123.dkr.ecr.eu-west-1.amazonaws.com/myimage:latest

docker push 123123123.dkr.ecr.eu-west-1.amazonaws.com/myimage:latest

**Comment by eugali** [comment] 2020-11-22 16:30
These are the info present in the Caprover edit box

User: AWS
Password: xxx
Domain: 123123123.dkr.ecr.eu-west-1.amazonaws.com/myimage
Image Prefix: [empty]

**Comment by githubsaturn** [comment] 2020-11-22 17:07
https://github.com/caprover/caprover/issues/434#issuecomment-731766975

**Comment by eugali** [comment] 2020-11-22 18:09
Setting 123456789.dkr.ecr.eu-west-1.amazonaws.com as domain and leaving Image Prefix empty -> not successful

Manual push with the above commands -> successful 

The data in the EDIT box are listed 2 comments above. 

What's missing?

**Comment by githubsaturn** [comment] 2020-11-22 18:20
> The data in the EDIT box are listed 2 comments above.

I am confused. In the comment above, you said you've set the domain to `123123123.dkr.ecr.eu-west-1.amazonaws.com/myimage` - NOT `123123123.dkr.ecr.eu-west-1.amazonaws.com`

Which one is that??

**Comment by eugali** [comment] 2020-11-22 19:19
I tried all the configurations, with and without the /myimage in the CapRover edit box. None of them work. The current one is the one with "myimage"

**Comment by githubsaturn** [comment] 2020-11-22 19:22
Of course the one with myimage won't work. Try these EXACT steps on your CapRover server.
```
## DO NOT USE AWS CLI
## DO NOT SUFFIX THE DOMAIN BELOW - JUST USE THE PLAIN DOMAIN WITHOUT HTTP AND WITHOUT ANY SUFFIX
docker login -u yourawsusername -p yourawspassword 123123123.dkr.ecr.eu-west-1.amazonaws.com

docker pull nginx
docker tag nginx 123123123.dkr.ecr.eu-west-1.amazonaws.com/img-captain-myapp:latest
docker push 123123123.dkr.ecr.eu-west-1.amazonaws.com/img-captain-myapp:latest
```

Does this work?

**Comment by eugali** [comment] 2020-11-22 19:43
Yep it works

**Closed** 2020-11-22 19:45 UTC

**Comment by githubsaturn** [comment] 2020-11-22 19:47
Okay - CapRover performs the same actions when you enter:
- `Domain: ` as `123123123.dkr.ecr.eu-west-1.amazonaws.com`
- and leave image prefix empty

So do this. Then create a new app, call it `test-app`

Go to deployment page, and from " Method 6: Deploy via ImageName" enter
```
123123123.dkr.ecr.eu-west-1.amazonaws.com/img-captain-myapp:latest
```

**Comment by githubsaturn** [comment] 2020-11-22 19:48
Does your image get deployed using this method?

**Comment by eugali** [comment] 2020-11-22 19:53
Just tried with test-app. I see the following lines:

Build started for test-app
An explicit image name was provided (375004285360.dkr.ecr.eu-west-1.amazonaws.com/img-captain-myapp:latest). Therefore, no build process is needed.
Pulling this image: 123123123.dkr.ecr.eu-west-1.amazonaws.com/img-captain-myapp:latest This process might take a few minutes.
Build has finished successfully!


In the main app the method 6 is not set

**Comment by githubsaturn** [comment] 2020-11-22 19:58
Okay - so CapRover authentication works, and pull works. Not sure what the problem is on your specific end. Suggest trying out another registry like Docker Hub or GitLab

**Comment by eugali** [comment] 2020-11-22 20:26
Did with docker hub, works perfectly. Thank you for your support.

**Comment by locvfx** [comment] 2022-12-13 07:41
I hit this error when deploying one-click app Browserless

Browserless Image Version
1-chrome-stable

So i chose 'latest' as image version to avoid this error. Unfortunately the issue still persists!
Can anyone help please?

**Comment by githubsaturn** [comment] 2022-12-14 04:15
Disable the push registry and try again.

![image](https://user-images.githubusercontent.com/10582082/207504310-3e8bd5e2-f917-4d20-adb8-c4c19f90b969.png)

**Comment by tomaskikutis** [comment] 2023-08-05 21:17
I have the same issue too.

```
Successfully built 84db6d5b16b6
Successfully tagged img-captain-my-app:latest
Build has failed!
----------------------
Deploy failed!
Error: Push failed: Error: (HTTP code 500) server error - invalid reference format
```

I'm running a self-hosted registry deployed from `registry:2` image from docker hub with no modifications apart from mapping a persistent directory, adding SSL and basic auth - all from caprover configs.

Did did try pulling nginx, pushing to my registry and then deploying a test app on caprover from that image as described in https://github.com/caprover/caprover/issues/434#issuecomment-731826924 and https://github.com/caprover/caprover/issues/434#issuecomment-731834321 comments and all worked well.

I've seen people on stackoverflow [speculating](https://stackoverflow.com/a/51208726) that the issue could be related with usage of `pwd` and it adding spaces to the path.

**Comment by githubsaturn** [comment] 2023-08-06 04:26
Is your app actually called `my-app`? Do you have double hyphens by any chance?

**Comment by tomaskikutis** [comment] 2023-08-06 04:38
It's not called `my-app`, but I don't have double hyphens. No other special symbols either - just lower case letters separated by a single hyphen as in `my-app`.

**Comment by githubsaturn** [comment] 2023-08-06 04:39
What about your root domain? A simple alphabetical domain name?

**Comment by tomaskikutis** [comment] 2023-08-06 06:22
yep, only letters

**Comment by githubsaturn** [comment] 2023-08-06 14:40
@tbroadley - I just tried to replicate and it worked fine on my end. One difference that I noticed is that I see:
```
Successfully tagged img-captain-myapp:latest
Pushing to remote: registry.cp.domain.com:996/captain/img-captain-myapp:29
.....
....
```

Do you not have this `Pushing to remote` line in your logs?
If not, it confirms that it fails after tagging and before pushing... which makes the debugging process a bit more clear.

**Comment by tomaskikutis** [comment] 2023-08-06 19:44
I don't have `Pushing to remote` in the logs.

Here's my complete output except docker build steps:

```
Uploading [====================] 100%  (ETA 0.0s)
Upload done.

This might take several minutes. PLEASE BE PATIENT...

Building your source code...

[[ TRUNCATED ]]

# DOCKER BUILD STEPS OMITTED

Successfully built 84db6d5b16b6
Successfully tagged img-captain-test-app:latest
Build has failed!
----------------------
Deploy failed!
Error: Push failed: Error: (HTTP code 500) server error - invalid reference format

Something bad happened. Cannot deploy test-app at captain-02.
```

**Comment by githubsaturn** [comment] 2023-08-06 23:00
That's really strange. The very first thing in the push function is to log "Pushing to remote"
https://github.com/caprover/caprover/blob/1e4f14ca2d2fd6f8bab57e6a2ca878a0f2d78c0a/src/docker/DockerApi.ts#L604-L609



My guess is that your deploy is failing somewhere else, but somehow Docker tags it as a push failure.... Anyways:

1- Just confirm, you're not using a self hosted registry, right? You just set up a registry manually as a separate app and manually enabled SSL, and set up volumes. Is my understanding correct?

2- Can you please confirm that you have a default push registry in your CLUSTER tab? 

3- Can you please get logs from the CapRover engine as well? They might have more info:
```
docker service logs captain-captain
```

**Comment by tomaskikutis** [comment] 2023-08-07 17:05
1. correct
2. yes I have
3. sure

```
August 7th 2023, 3:41:41.857 pm    Building docker image. This might take a few minutes...
August 7th 2023, 3:41:42.213 pm    Docker Auth is found. Pushing the image...
August 7th 2023, 3:41:42.217 pm    Error: Wrapped: PUSH FAILED
Error: Wrapped: PUSH FAILED
    at errorize (/usr/src/app/built/utils/Logger.js:7:16)
    at Function.e (/usr/src/app/built/utils/Logger.js:27:21)
    at /usr/src/app/built/user/DockerRegistryHelper.js:59:42
    at new Promise (<anonymous>)
    at /usr/src/app/built/user/DockerRegistryHelper.js:58:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
August 7th 2023, 3:41:42.217 pm    Error: (HTTP code 500) server error - invalid reference format 
Error: (HTTP code 500) server error - invalid reference format 
    at /usr/src/app/node_modules/docker-modem/lib/modem.js:315:17
    at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:345:7)
    at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:314:5)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:286:14)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
August 7th 2023, 3:41:42.234 pm    Error: Push failed: Error: (HTTP code 500) server error - invalid reference format 
Error: Push failed: Error: (HTTP code 500) server error - invalid reference format 
    at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:8:16)
    at /usr/src/app/built/user/DockerRegistryHelper.js:61:57
    at new Promise (<anonymous>)
    at /usr/src/app/built/user/DockerRegistryHelper.js:58:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
GET /api/v2/user/apps/appData/test-app 200 1.157 ms - 1415
```

I tried to edit `/usr/src/app/built/user/DockerRegistryHelper.js` to log `fullImageName`, then started a new deploymet, but changes weren't taking effect. Any idea why?

**Comment by githubsaturn** [comment] 2023-08-08 01:02
You can't live-edit nodejs code. NodeJS caches the code on start up. The only way is to restart the app and that will restart the docker image and your changes will be gone... 

Given that the error happens without seeing `pushing to remote`, this has to happen here:
https://github.com/caprover/caprover/blob/1e4f14ca2d2fd6f8bab57e6a2ca878a0f2d78c0a/src/docker/DockerApi.ts#L597-L600

Anyways, to be able to log the fullImageName name, do this:
1) Run this on your host
```
echo "FROM caprover/caprover\nCMD sleep 99d" > /tmp/sleeping-caprover
docker build -f /tmp/sleeping-caprover -t sleeping-caprover .
docker service update captain-captain --image sleeping-caprover
```

2) Test the new image by shelling into the container and starting a node process:
```
docker exec -it $(docker ps --filter name=captain-captain -q) /bin/sh
```
now that you're in the container, run `node built/server.js`

3) Confirm that CapRover works normally

4) now you can stop the node process, edit any files and run node again to get more debug.

**Comment by tomaskikutis** [comment] 2023-08-08 19:49
```
Pushing to remote: registry.mydomain.com/img-captain-my-app:10
Server: registry.mydomain.com
This might take a few minutes...
Push succeeded...
Build has finished successfully!
```

Even though it says it has built and pushed sucessfully, I now get "Nothing here yet :/" when I visit the site which I assume might be because of those double slashes used somewhere else as well to find the image, but I'm not sure.

**Comment by githubsaturn** [comment] 2023-08-09 01:21
It might be because of that... Try running `docker service ls` to see if the right image is being deployed.

The better approach is to use a non-empty image prefix. You can use `images` or anything really.... We should make the field "required" in the UI to avoid this bug.

**Comment by Reza1290** [comment] 2024-09-15 12:22
push via cli

1. login
`docker login -u "myusername" -p "mypassword" docker.io
`
2. create repo or remote

```
docker tag local-image:tagname new-repo:tagname
docker push new-repo:tagname
```

ex:
```
docker tag ciptakode:latest reza1290/ciptakode:latest
docker push reza1290/ciptakode:latest
```
