### ISSUE TITLE
Problem with Fusionauth

### ISSUE THREAD

**Issue by ricalexm** [caprover/caprover#1035] opened 2021-02-25 18:27 UTC
What is the problem?
The latest version of caprover (1.9.0) has an issue proxying requests to Fusionauth. 
This is a caprover specific issue as it works well on a previous version.

The error that fusionauth shows on its logs is the following:
```
io.fusionauth.app.primeframework.error.ExceptionExceptionHandler - An unhandled exception was thrown
2021-02-19T12:33:25.901133267Z java.lang.UnsupportedOperationException: You are attempting to map a form field that contains multiple parameters to a property on the action class that is of type java.net.URI. This isn't allowed.
2021-02-19T12:33:25.901164240Z at org.primeframework.mvc.parameter.convert.converters.URIConverter.stringsToObject(URIConverter.java:57)
2021-02-19T12:33:25.901173143Z at org.primeframework.mvc.parameter.convert.AbstractGlobalConverter.convertFromStrings(AbstractGlobalConverter.java:89)
2021-02-19T12:33:25.901179950Z at org.primeframework.mvc.parameter.el.Accessor.convert(Accessor.java:152)
2021-02-19T12:33:25.901186348Z at org.primeframework.mvc.parameter.el.MemberAccessor.set(MemberAccessor.java:133)
2021-02-19T12:33:25.901193307Z at org.primeframework.mvc.parameter.el.Accessor.set(Accessor.java:90)
2021-02-19T12:33:25.901199032Z at org.primeframework.mvc.parameter.el.Expression.setCurrentValue(Expression.java:93)
2021-02-19T12:33:25.901205133Z at org.primeframework.mvc.parameter.el.DefaultExpressionEvaluator.setValue(DefaultExpressionEvaluator.java:132)
2021-02-19T12:33:25.901215115Z at org.primeframework.mvc.parameter.DefaultParameterHandler.setValues(DefaultParameterHandler.java:205)
2021-02-19T12:33:25.901222236Z at org.primeframework.mvc.parameter.DefaultParameterHandler.handle(DefaultParameterHandler.java:121)
2021-02-19T12:33:25.901250341Z at org.primeframework.mvc.parameter.DefaultParameterWorkflow.perform(DefaultParameterWorkflow.java:54)
2021-02-19T12:33:25.901257749Z at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
2021-02-19T12:33:25.901264389Z at org.primeframework.mvc.parameter.DefaultURIParameterWorkflow.perform(DefaultURIParameterWorkflow.java:102)
2021-02-19T12:33:25.901270866Z at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
2021-02-19T12:33:25.901277173Z at org.primeframework.mvc.scope.DefaultScopeRetrievalWorkflow.perform(DefaultScopeRetrievalWorkflow.java:58)
2021-02-19T12:33:25.901283463Z at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
2021-02-19T12:33:25.901290026Z at org.primeframework.mvc.message.DefaultMessageWorkflow.perform(DefaultMessageWorkflow.java:44)
2021-02-19T12:33:25.901307114Z at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
2021-02-19T12:33:25.901328377Z at io.fusionauth.app.primeframework.FrontEndTenantWorkflow.perform(FrontEndTenantWorkflow.java:183)
2021-02-19T12:33:25.901331919Z at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
2021-02-19T12:33:25.901335271Z at org.primeframework.mvc.action.DefaultActionMappingWorkflow.perform(DefaultActionMappingWorkflow.java:126)
2021-02-19T12:33:25.901338621Z at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
2021-02-19T12:33:25.901342429Z at org.primeframework.mvc.workflow.StaticResourceWorkflow.perform(StaticResourceWorkflow.java:97)
2021-02-19T12:33:25.901345831Z at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
2021-02-19T12:33:25.901349211Z at org.primeframework.mvc.parameter.RequestBodyWorkflow.perform(RequestBodyWorkflow.java:89)
2021-02-19T12:33:25.901352531Z at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
2021-02-19T12:33:25.901355877Z at org.primeframework.mvc.security.DefaultSavedRequestWorkflow.perform(DefaultSavedRequestWorkflow.java:64)
2021-02-19T12:33:25.901359311Z at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
2021-02-19T12:33:25.901362612Z at io.fusionauth.app.primeframework.CORSFilter.doFilter(CORSFilter.java:240)
2021-02-19T12:33:25.901366026Z at io.fusionauth.app.primeframework.CORSRequestWorkflow.perform(CORSRequestWorkflow.java:48)
2021-02-19T12:33:25.901369307Z at org.primeframework.mvc.workflow.SubWorkflowChain.continueWorkflow(SubWorkflowChain.java:51)
2021-02-19T12:33:25.901372602Z at io.fusionauth.app.primeframework.FusionAuthMVCWorkflow.perform(FusionAuthMVCWorkflow.java:88)
2021-02-19T12:33:25.901375987Z at org.primeframework.mvc.workflow.DefaultWorkflowChain.continueWorkflow(DefaultWorkflowChain.java:44)
2021-02-19T12:33:25.901379372Z at org.primeframework.mvc.servlet.FilterWorkflowChain.continueWorkflow(FilterWorkflowChain.java:50)
2021-02-19T12:33:25.901383017Z at org.primeframework.mvc.servlet.PrimeFilter.doFilter(PrimeFilter.java:78)
2021-02-19T12:33:25.901386369Z at com.inversoft.maintenance.servlet.MaintenanceModePrimeFilter.doFilter(MaintenanceModePrimeFilter.java:59)
2021-02-19T12:33:25.901399570Z at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2021-02-19T12:33:25.901403420Z at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2021-02-19T12:33:25.901406768Z at com.inversoft.servlet.UTF8Filter.doFilter(UTF8Filter.java:27)
2021-02-19T12:33:25.901410612Z at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
2021-02-19T12:33:25.901414032Z at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
2021-02-19T12:33:25.901421502Z at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
2021-02-19T12:33:25.901424982Z at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
2021-02-19T12:33:25.901428243Z at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
2021-02-19T12:33:25.901431497Z at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
2021-02-19T12:33:25.901434852Z at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
2021-02-19T12:33:25.901438095Z at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
2021-02-19T12:33:25.901441368Z at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
2021-02-19T12:33:25.901444597Z at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
2021-02-19T12:33:25.901447943Z at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
2021-02-19T12:33:25.901451192Z at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
2021-02-19T12:33:25.901454453Z at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
2021-02-19T12:33:25.901457783Z at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2021-02-19T12:33:25.901461117Z at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
2021-02-19T12:33:25.901464460Z at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
2021-02-19T12:33:25.901478118Z at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2021-02-19T12:33:25.901481558Z at java.base/java.lang.Thread.run(Thread.java:832)
```

Workaround: Rollback to a previous version and don't update caprover to the latest version (1.9.0).

If applicable, content of `captain-definition` file:
N/A

Steps to reproduce the problem:
1) Install fusionauth using the template (or manually)
2) After install, configure it.
3) You will not be able to access it again after that initial setup.

**Comment by githubsaturn** [comment] 2021-02-26 00:03
> Workaround: Rollback to a previous version and don't update caprover to the latest version (1.9.0).

Did you try this and it works?

Does it work if you roll back CapRover to a previous version after installation? Or do you have to rollback before installing fusionauth?

**Comment by ricalexm** [comment] 2021-02-26 00:05
It works. That's what I used.

I had an existing fusionauth installation that stopped working on version
1.9.0 and after I rolled back to 1.8.2, fusionauth started working again.

**Comment by githubsaturn** [comment] 2021-02-26 00:07
Okay - I just tried it and it worked fine:

![image](https://user-images.githubusercontent.com/10582082/109235975-bcbc6980-779c-11eb-842e-4453e70142a4.png)

**Comment by githubsaturn** [comment] 2021-02-26 00:09
I think it may "coincided" with your CapRover upgrade, but probably unrelated. Looking at the [changelog for 1.9.0](https://github.com/caprover/caprover/blob/master/CHANGELOG.md#190---2021-02-15), there is really nothing that can remotely be causing this.

**Comment by ricalexm** [comment] 2021-02-26 00:11
When I tested it, a clean install works fine for setup and initial access. As soon as you logout that error starts being thrown on fusionauth and you are never able to login again.

**Comment by ricalexm** [comment] 2021-02-26 00:15
Interesting. What may have caused it? I didn't customise anything on the caprover side. I was using an app without any modifications at the NGINX level, and I configured it the same way the one click template is configured.

**Comment by githubsaturn** [comment] 2021-02-26 00:20
Once your install an app, CapRover is completely out of the picture. You can literally run
```
docker service scale captain-captain=0
```
And you'll see that your app continues to run just fine.


> What may have caused it?

I am not sure. I don't rule out possibility of some weird thing in 1.9.0, but it's highly unlikely. I suggest you try upgrading to 1.9.0 and see if the issue happens again, and when you rollback it resolve itself.

Give it a shot. If that does happen, I'll write up more debugging steps for you to get to the bottom of it.

**Comment by ricalexm** [comment] 2021-02-26 00:29
Just updated captain again to version 1.9.0 and fusionauth stoped working again with the same error.

**Comment by githubsaturn** [comment] 2021-02-26 00:43
Okay this is super weird. I'll leave this issue for a week or so to see if anyone else is experiencing this issue. 

In the meantime, I recommend you open an issue on FusionAuth tracker to see if they have any idea where this error is coming from.

**Comment by githubsaturn** [comment] 2021-02-26 00:54
I tried installing it on a fresh version and it works just fine. Tried logging out and logging back in.

If you want to try out
Here is the instance: http://captain.ip172-18-0-47-c0s49kre75e000co4aig-80.direct.labs.play-with-docker.com/
password: captain42


Here is fusionauth: http://fusionauth-fusionauth.ip172-18-0-47-c0s49kre75e000co4aig-80.direct.labs.play-with-docker.com/
```
email: noreply@gmail.com
password: captain42
```

The instance should remain alive for the next hour or so if you want to try it out.

**Comment by ricalexm** [comment] 2021-02-26 00:58
One thing I noticed on that fusionauth instance is that that's version 1.7.2 (an almost 2-year-old release). The most recent release is 1.24.0.

**Comment by githubsaturn** [comment] 2021-02-26 01:22
> One thing I noticed on that fusionauth instance is that that's version 1.7.2 (an almost 2-year-old release). The most recent release is 1.24.0.

Do you have 1.24.0 installed?

**Comment by ricalexm** [comment] 2021-02-26 01:41
Yes

**Comment by githubsaturn** [comment] 2021-02-26 01:48
Ah okay, then how do you reproduce the issue. In your original post you mentioned: "Install fusionauth using the template", but the template is using 1.7.2

**Comment by githubsaturn** [comment] 2021-02-26 01:49
And you cannot (should not) assume that you can just bump the version and everything should work. Env vars, configs and etc may change between versions, that's why we lock the one click app versions and we do not use `latest` tag.

**Comment by githubsaturn** [comment] 2021-03-04 00:47
Thanks for the additional info! That explains it!

Go to your app, click on EDIT NGINX CONFIG, find this line:
```
            return 302 https://$http_host$request_uri$is_args$query_string;
```
remove this part: `$is_args$query_string`

Save and Update and it should fix the issue. Since the issue is minor (only an issue for FusionAuth), I won't be cutting a hotfix for this, you can manually update nginx config to get this working. But the fix will be in the next version.

**Closed** 2021-03-04 00:49 UTC

**Comment by douglasjunior** [comment] 2021-05-03 14:34
We noticed another problem here related to "force https". When redirects occurs, the query params are duplicated. Example:

- From: http://mydomain.com/redirect?token=c06b92d1-d7c7-4efc-80a7-b2d8a6e03911
- To: https://mydomain.com/redirect?token=c06b92d1-d7c7-4efc-80a7-b2d8a6e03911?token=c06b92d1-d7c7-4efc-80a7-b2d8a6e03911

Removing the `$is_args$query_string` fixes the issue.

**Comment by githubsaturn** [comment] 2021-05-03 22:51
@douglasjunior  - it's already fixed here: https://github.com/caprover/caprover/commit/15291fb4018b42544b03cb6ffda577d2549ef444

It'll be included in the next build.

**Comment by douglasjunior** [comment] 2021-05-04 11:14
I saw it, thanks! ❤️

I commented just to inform you that it's not just a problem with FusionAuth.  😆

**Comment by prasannjeet** [comment] 2024-10-14 21:37
If someone still faces this issue, you just need to enable "Websocket Support" in Caprover's HTTP settings for fusion auth.
