### ISSUE TITLE
Making Caprover IPv6 aware

### ISSUE THREAD

**Issue by PaulKlumpp** [caprover/caprover#1285] opened 2021-12-16 16:06 UTC
**Is your feature request related to a problem? Please describe.**
As IPv4 addresses are more and more rare - and ISPs are now giving out IPv6-prefixes more freely and often without charge, it may be a natural advancement to have Caprover IPv6-aware.

**Describe the solution you'd like**
When setting up Caprover, it asks for a wildcard Type A DNS record. It could also ask for a Type AAAA DNS record.
Also, just by trying to enter my AAAA record, it gives an error "1107 : Verification Failed".
Funny enough, the website (port 3000) was already hosted using a AAAA record.
![grafik](https://user-images.githubusercontent.com/1990861/146407605-222e9f0d-24ed-40d9-99b6-212e16d40fd4.png)

Docker internal network may still be IPv4 or both, or IPv6 only. But exposing the endpoint with IPv6 should be quite easy, as Docker daemon already binds on all interfaces.

**Describe alternatives you've considered**

**Additional context**
Also, "caprover serversetup" asks for IPv4 only. When entering an IPv6, it tells me, the IP address was invalid.
![grafik](https://user-images.githubusercontent.com/1990861/146406671-0707af06-d26e-4e65-ba55-3ec118f75e9b.png)

**Comment by githubsaturn** [comment] 2021-12-16 17:25
Duplicate of https://github.com/caprover/caprover/issues/594

**Closed by githubsaturn** 2021-12-16 17:25 UTC
