### ISSUE TITLE
Cannot connect new domain

### ISSUE THREAD

**Issue by eikaramba** [caprover/caprover#1455] opened 2022-06-30 12:49 UTC
First of CapRover works, even with SSL on the dashboard and searching of One-Click Apps (already installed two)

# Problem:
I setup a new A Record for `api.foodolyst.creatness.studio` to point to my server adress and trying to add it as a new domain for an app. I immediately get `1107 : Verification Failed`.

https://mxtoolbox.com/SuperTool.aspx?action=a%3aapi.foodolyst.creatness.studio&run=toolpage
![grafik](https://user-images.githubusercontent.com/1320525/176679366-40839177-f807-459d-86ae-ba46df000a69.png)

# Investigation:
logs from `docker service logs captain-captain -f`
```
POST /api/v2/user/apps/appDefinitions/customdomain 200 7.509 ms - 62
Sending request to http://api.foodolyst.creatness.studio/.well-known/captain-identifier
Error: Verification Failed.
     at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:8:16)
     at Request._callback (/usr/src/app/built/user/system/DomainResolveChecker.js:79:53)
     at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
     at Request.emit (events.js:400:28)
     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
     at ClientRequest.emit (events.js:400:28)
     at Socket.socketErrorListener (_http_client.js:475:9)
     at Socket.emit (events.js:400:28)
     at emitErrorNT (internal/streams/destroy.js:106:8)
     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
```

When i login to the captain container via `docker exec -it $(docker ps --filter name=captain-captain -q) /bin/sh` and then try to ping the url with  `curl http://api.foodolyst.creatness.studio/.well-known/captain-identifier -v` i get

```
# curl http://api.foodolyst.creatness.studio/.well-known/captain-identifier -v
*   Trying 10.0.1.7...
* TCP_NODELAY set
* connect to 10.0.1.7 port 80 failed: Connection refused
* Failed to connect to api.foodolyst.creatness.studio port 80: Connection refused
* Closing connection 0
```

10.0.1.7 is the correct ip of the app container i am trying to connect to.

Pinging the root domain of my captain instance however works and resolves to the correct server ip.
```
Trying 185.244.192.144...
* TCP_NODELAY set
* Connected to xxxxxxx.creatness.studio (185.244.192.144) port 80 (#0)
> GET /.well-known/captain-identifier HTTP/1.1
> Host: xxxxxxx.creatness.studio
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
.....
<
* Curl_http_done: called premature == 0
* Connection #0 to host xxxxx.creatness.studio left intact
```

This makes me belive that it is somehow maybe related to DNS resolving issues ([related ticket](https://github.com/caprover/caprover/issues/621)). I already tried the following:

- Restart Server as suggested [here](https://github.com/caprover/caprover/issues/502)
- Restart Captain via `docker service update captain-captain --force`
- disable UFW

Docker itself seems to not have this problem, as i can successfully do `docker run --rm curlimages/curl:7.81.0 -L -v  http://api.foodolyst.creatness.studio/.well-known/captain-identifier`

I can also ping `10.0.1.7` from within the docker container.

# Infos
I installed CapRover on Ubuntu 22.04 and followed the official docker installation guide, caprover guide and only installed tailscale ssh additionally. I also used UFW rules accordingly to caprover

**Comment by eikaramba** [comment] 2022-06-30 13:29
okay from within the caprover container i can do
```
ping api.foodolyst.creatness.studio

PING api.foodolyst.creatness.studio (10.0.1.7) 56(84) bytes of data.
64 bytes from srv-captain--foodolyst-backend.1.50qwttmc8tf3w8idxlf4ctwkz.captain-overlay-network (10.0.1.7): icmp_seq=1 ttl=64 time=0.120 ms
```
So the internal network seems to work? but port 80 is rejected? i am out of ideas and really happy about any insights :)

**Comment by eikaramba** [comment] 2022-06-30 13:34
skipping the verifiyingdomains check works btw.
`echo  "{\"skipVerifyingDomains\":\"true\"}" >  /captain/data/config-override.json && docker service update captain-captain --force`

After that i am able to connect the domain and even setup SSL. still i think it make sense to get to the bottom of this issue

**Comment by githubsaturn** [comment] 2022-06-30 14:04
> 10.0.1.7 is the correct ip of the app container i am trying to connect to.

This shouldn't be the case. When you ping `api.foodolyst.creatness.studio` the IP address that you should see is the IP address of your host `185.244.192.144`... I wonder if it's because of tailscale messing up with the network interfaces. Try reproducing it on a host that doesn't have tailscale and see if it works.

**Comment by maietta** [comment] 2022-07-13 15:52
Hi @eikaramba. Has there been any resolution to this problem?

I don't think this is a problem with Caprover but it'd be good to close this if the problem is resolved or continue troubleshooting if it hasn't.

Thanks.

**Closed** 2022-07-14 11:16 UTC

**Comment by joingardens** [comment] 2022-09-09 10:35
@eikaramba @maietta @githubsaturn  We were actually able to reproduce this same error by using Dreamhost domain provider and provisioning subdomains via their API. For some reason verification fails even though MX toolbox lookup for the subdomain shows DNS are setup properly

**Comment by githubsaturn** [comment] 2022-09-10 22:31
@joingardens  - that's not necessary the same issue. Sometimes your VPS setup is blocking the loopback. In that case, you can disable the verification that CapRover performs:

https://caprover.com/docs/troubleshooting.html#domain-verification-failed---error-1107
