### ISSUE TITLE
Folder Support for better organization

### ISSUE THREAD

**Issue by ErSauravAdhikari** [caprover/caprover#1223] opened 2021-10-12 05:01 UTC
I have a caprover instance hosted on a single server where I host all of my applications. But the list has gotten kinda large, and sometimes it is frustrating to find the app you are looking for on that long list.

So I was wondering if would be quite good if we could categorize the applications into some things like a folder or group so that in the dashboard I see the name of the group within which I see all the applications belonging to the group and my root dashboard remains clutter-free and the navigation would be super easy.

**Comment by githubsaturn** [comment] 2021-10-13 00:37
Duplicate of https://github.com/caprover/caprover-frontend/issues/52

**Closed by githubsaturn** 2021-10-13 00:37 UTC
