### ISSUE TITLE
webhook url on app autodeploy configuration section does not populate after entering repo/key info

### ISSUE THREAD

**Issue by sneak** [caprover/caprover#609] opened 2020-03-04 23:41 UTC
# problem

When I set up a new app to be autobuilt from a remote repo using an SSH key, the webhook URL does not autopopulate without a page reload (which entails logging back in to CapRover).

# reproduction

1. create new app
1. click on app
1. go to deployment tab
1. put in repo URL
1. type in branch name
1. paste ssh private key
1. hit "save and update"

# expected

webhook URL is populated

# actual

the descriptive text stays there

# workaround

reload page, log back in, click on appname, click on deployment tab - webhook url is populated

# system info

caprover version: 1.6.1

**Comment by sneak** [comment] 2020-03-04 23:42
PS: webhook-based autobuilds are the killer feature of caprover and i can't stress enough how grateful i am that you made this software, it makes my life about a million times easier.

**Comment by githubsaturn** [comment] 2020-03-05 01:26
> PS: webhook-based autobuilds are the killer feature of caprover and i can't stress enough how grateful i am that you made this software, it makes my life about a million times easier.

Happy to hear that :blush: :pray: 

> When I set up a new app to be autobuilt from a remote repo using an SSH key, the webhook URL does not autopopulate without a page reload (which entails logging back in to CapRover).

This is a duplicate of https://github.com/caprover/caprover-frontend/issues/41

**Closed by githubsaturn** 2020-03-05 01:26 UTC
