### ISSUE TITLE
caprover almost dos-ing docker.io

### ISSUE THREAD

**Issue by doebi** [caprover/caprover#1547] opened 2022-10-29 07:24 UTC
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

What is the problem?

More by accident than intentional I had my caprover instance hooked up to my pi-hole running on a different server. From the dashboard I saw that the server running caprover is sending a lot of requests to docker.io.

![2022-10-29_09-11](https://user-images.githubusercontent.com/1591457/198819147-4fe9a0d2-3d2a-46de-b449-c9c609b33707.png)

While 1000req in 15min do not fully qualify as a DOS attack, I still think this is way too much for an idling server. I have no active deployments or upgrades running.

This might also explain why some users experience quota issues at docker.io (including myself)

Has anyone else experienced similar behavior, or can tell me whats going on?

Caprover does not really offer much insight on what itself is doing. Maybe a simple dashboard with some key metrics would help to discover such "issues" or misconfigurations earlier. Since the day I first installed I am wating for the "congratulations!" popup at the dashboard tab to disappear and show me some real dashboard. Is this a planned feature?

Any inputs appreciated.
Thanks

Output of the following command on your server:

```
$ uname -a && lsb_release -a && free -h
Linux doebi.at 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
              total        used        free      shared  buff/cache   available
Mem:          5.8Gi       3.2Gi       722Mi       109Mi       1.9Gi       3.1Gi
Swap:         808Mi       312Mi       496Mi

```

I am running caprover:1.10.1

**Comment by maietta** [comment] 2022-10-29 15:35
The "Dashboard" link just takes you to the "Congratulations " notice, nothing interesting there except a button to take you to where you can change the root domain. There is no "dashboard". Until now, I never much paid attention to the fact that there's a dashboard link but no dashboard. To be clear, this is normal behavior despite perhaps not being very intuitive.

The mere fact you are seeing so many requests from the docker container registry tells me something is amiss and it's time to isolate the server from the web until you can figure out what's going on. Don't know if this behavior is nefarious or if there is a perfectly good explanation for it.

**Comment by githubsaturn** [comment] 2022-10-29 15:48
Everytime you update a service (Save & Update) button, if the image is hosted on dockerhub, docker.io [gets pinged](https://github.com/caprover/caprover/blob/e23b3c7d8af103c6c6dc4cea2973737daabf6e22/src/docker/DockerApi.ts#L1467-L1473). Without this block, if you have a cluster (multiple nodes), the worker nodes fail to pull the image. 

Other than this, there is [no other area](https://github.com/caprover/caprover/search?q=docker.io&type=code) where docker.io is involved. Do you see the number just keeps going up even if you don't do any actions?

In fact, I too have a CapRover instance routing through PiHole, but I don't see this huge number of pings. What other services are you running on your machine. It's very likely that it's something else.

**Comment by doebi** [comment] 2022-10-31 12:32
Caprover was trying to redeploy a not fully-configured container over and over again. It was looking for a custom image at the cluster-local registry, didn't find it and was looking at docker.io. 

Probably a rather rare case, with me being sloppy with my trials and tests.

Still this could be turned into an enhancement request of either halting a redeploy after X failed tries. Or, as mentioned before, a dashboard with visuals hinting at irregular behaviour.

**Comment by githubsaturn** [comment] 2022-11-01 04:56
CapRover doesn't do any retry on build failures. Do you have a reproducible case? I am guessing it's actually docker engine that might be retrying.

**Comment by doebi** [comment] 2022-11-01 06:55
No, sorry I just straight away deleted the container in question.

This is the corresponding logline from "daemon.log":
```
Oct 30 00:00:25 doebi dockerd[6893]: time="2022-10-30T00:00:25.392975819Z" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
Oct 30 00:00:25 doebi dockerd[6893]: time="2022-10-30T00:00:25.397052730Z" level=info msg="Ignoring extra error returned from registry: unauthorized: authentication required"
Oct 30 00:00:25 doebi dockerd[6893]: time="2022-10-30T00:00:25.397375468Z" level=error msg="pulling image failed" error="pull access denied for img-captain-mysql-db, repository does not exist or may require 'docker login': denied: requested access to the resource is denied" module=node/agent/taskmanager node.id=appf9lf30yoyy85ncep9kstpk service.id=y06l6jpqqqw8m63o6kcz1sd65 task.id=fzdb8v0em6jn4gz4fzl45orf9
Oct 30 00:00:25 doebi dockerd[6893]: time="2022-10-30T00:00:25.416170106Z" level=error msg="fatal task error" error="No such image: img-captain-mysql-db:1" module=node/agent/taskmanager node.id=appf9lf30yoyy85ncep9kstpk service.id=y06l6jpqqqw8m63o6kcz1sd65 task.id=fzdb8v0em6jn4gz4fzl45orf9
```

This happened every 5 seconds for (probably) months.

Luckily logrotation prevented me from disk flood. Since this is my testing machine I didn't have proper monitoring and apart from docker login nothing complained about the spam.

**Comment by doebi** [comment] 2022-11-01 07:01
This issue might be related to #1189 
But I cannot reproduce it properly, since I don't have logs anymore.

**Comment by githubsaturn** [comment] 2022-11-02 01:33
Yea it is very likely the root cause for #1189, but certainly it's not CapRover that is retrying, it's the Docker daemon. 

Closing this issues as it's not really CapRover specific based on the logs that you shared. Feel free to reopen if you see this being done by CapRover.

**Closed by githubsaturn** 2022-11-02 01:33 UTC
