### ISSUE TITLE
one-click apps: passwords not working

### ISSUE THREAD

**Issue by FloMaetschke** [caprover/caprover#376] opened 2019-02-23 11:35 UTC
When i create a new one-click app (wordpress or strapi) it finishes successfully.
After that, the app tries to login to the database and ends up with an endless retry loop unable to connect.

At the database log, i can see that there is a connection attemp which is responded with access denied.

I guess the password defined in the frontend are not working?

db log:

```
 019-02-23T11:40:58.322998473Z 2019-02-23T11:40:58.322952Z 0 [Note] mysqld: ready for connections.
2019-02-23T11:40:58.323012398Z Version: '5.7.25' socket: '/var/run/mysqld/mysqld.sock' port: 3306 MySQL Community Server (GPL)
2019-02-23T11:41:02.278528506Z 2019-02-23T11:41:02.278365Z 2 [Note] Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:05.279992445Z 2019-02-23T11:41:05.279826Z 3 [Note] Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:08.281459644Z 2019-02-23T11:41:08.281275Z 4 [Note] Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:11.282682467Z 2019-02-23T11:41:11.282545Z 5 [Note] Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:14.284360032Z 2019-02-23T11:41:14.284160Z 6 [Note] Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:17.285821859Z 2019-02-23T11:41:17.285660Z 7 [Note] Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:20.287672330Z 2019-02-23T11:41:20.287508Z 8 [Note] Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
```

wordpress log:

```
2019-02-23T11:41:45.045607663Z 
2019-02-23T11:41:45.045647203Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:41:45.045657407Z 
2019-02-23T11:43:00.448630110Z 
2019-02-23T11:41:45.045673476Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:43:00.448688511Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:41:48.047228481Z 
2019-02-23T11:43:00.448727745Z 
2019-02-23T11:41:48.047254860Z 
2019-02-23T11:41:48.047286291Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:43:00.448741253Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:48.047258775Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:43:03.450221007Z 
2019-02-23T11:41:51.048799700Z 
2019-02-23T11:43:03.450244591Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:41:51.048830713Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:43:03.450304708Z 
2019-02-23T11:41:51.048841428Z 
2019-02-23T11:43:03.450330820Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:51.048869889Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:43:06.451821861Z 
2019-02-23T11:41:54.050014600Z 
2019-02-23T11:43:06.451842480Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:41:54.050038142Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:43:06.451850879Z 
2019-02-23T11:41:54.050108325Z 
2019-02-23T11:43:06.451864334Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:54.050121356Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:57.051499201Z 
2019-02-23T11:41:57.051515546Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:41:57.051574547Z 
2019-02-23T11:41:57.051584973Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:42:00.052925791Z 
2019-02-23T11:42:00.052946283Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:42:00.053053001Z 
2019-02-23T11:42:00.053066938Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:42:03.054370929Z 
2019-02-23T11:42:03.054395716Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:42:03.054428890Z 
2019-02-23T11:42:03.054451169Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:42:06.056259422Z 
2019-02-23T11:42:06.056286496Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:42:06.056318120Z 
2019-02-23T11:42:06.056369634Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:42:09.057871319Z 
2019-02-23T11:42:09.057891474Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:42:09.057935823Z 
2019-02-23T11:42:09.057946954Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:42:23.969075828Z 
2019-02-23T11:42:23.969114420Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:42:23.969156254Z 
2019-02-23T11:42:23.969167721Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:42:26.970356742Z 
2019-02-23T11:42:26.970377991Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:42:26.970438300Z 
2019-02-23T11:41:02.278573250Z 
2019-02-23T11:42:26.970449946Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:42:12.059060029Z 
2019-02-23T11:41:02.278614709Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:42:29.971827838Z 
2019-02-23T11:42:12.059082999Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:41:02.278641401Z 
2019-02-23T11:42:12.059140217Z 
2019-02-23T11:42:29.971851101Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:41:02.278655674Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:42:29.972101510Z 
2019-02-23T11:41:05.280025145Z 
2019-02-23T11:42:29.972121828Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:05.280049377Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:42:12.059151307Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:42:32.973421308Z 
2019-02-23T11:41:05.280080241Z 
2019-02-23T11:42:32.973442246Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:41:05.280096396Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:42:32.973504368Z 
2019-02-23T11:41:08.281541962Z 
2019-02-23T11:42:32.973519258Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:08.281561738Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:42:35.974424814Z 
2019-02-23T11:41:08.281602435Z 
2019-02-23T11:42:35.974446276Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:41:08.281617723Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:11.282710454Z 
2019-02-23T11:42:35.974499330Z 
2019-02-23T11:41:11.282728921Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:42:35.974510516Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:42:38.975717284Z 
2019-02-23T11:41:11.282766289Z 
2019-02-23T11:42:38.975735538Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:41:11.282778264Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:42:38.975730683Z 
2019-02-23T11:41:14.284401917Z 
2019-02-23T11:42:38.975749670Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:14.284430380Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:42:41.976908377Z 
2019-02-23T11:41:14.284496222Z 
2019-02-23T11:42:41.976936580Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:41:14.284519508Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:17.285881851Z 
2019-02-23T11:42:41.976911273Z 
2019-02-23T11:41:17.285905255Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:42:41.976960828Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:17.285925767Z 
2019-02-23T11:41:17.285937512Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:42:44.978079572Z 
2019-02-23T11:42:44.978108956Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:41:20.287804487Z 
2019-02-23T11:41:20.287832547Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:42:44.978098046Z 
2019-02-23T11:41:20.287898603Z 
2019-02-23T11:42:44.978156080Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:42:47.979055571Z 
2019-02-23T11:41:20.287920932Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:23.289332012Z 
2019-02-23T11:42:47.979073244Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:41:23.289355968Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:42:47.979129825Z 
2019-02-23T11:41:23.289465803Z 
2019-02-23T11:42:47.979141535Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:23.289501005Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:42:50.980225190Z 
2019-02-23T11:41:26.290600036Z 
2019-02-23T11:42:50.980247638Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:42:50.980264143Z 
2019-02-23T11:41:26.290621172Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:41:26.290651176Z 
2019-02-23T11:41:26.290663178Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:42:50.980279306Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
2019-02-23T11:41:29.292000540Z 
2019-02-23T11:41:29.292024599Z Warning: mysqli::__construct(): (HY000/1045): Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES) in Standard input code on line 22
2019-02-23T11:41:29.292146870Z 
2019-02-23T11:41:29.292158991Z MySQL Connection Error: (1045) Access denied for user 'wordpressuser'@'10.0.0.5' (using password: YES)
```

**Comment by FloMaetschke** [comment] 2019-02-23 11:52
Ok, using mysql 5.5 instead of 5.7 fixed the problem.
I guess there is a breaking change in the new version

**Comment by githubsaturn** [comment] 2019-02-23 17:42
What version of CapRover are you using?

**Comment by FloMaetschke** [comment] 2019-02-23 23:18
latest

**Comment by githubsaturn** [comment] 2019-02-24 00:34
Just tested WordPress with this config:
- CapRover v1.2.1
- One Click WordPress
- WP version: 4.9 (selected by default)
- MySQL version: 5.7 (selected by default)
- Password `something123alphanumberic`

And it worked fine. This should not be host dependent. It is very confusing that you're getting this error. Can you double check the versions that you're using and let me know how it goes?

**Comment by FloMaetschke** [comment] 2019-02-25 18:01
I tried it again, now it works. 👍 

Strange thing, as you can see my logs in my previuos posts, it really happened.

**Comment by FloMaetschke** [comment] 2019-02-25 18:14
Could you please try to install strapi (all settings default)
pw: Something1234

It keeps starting up and stops

> -02-25T18:12:43.967852493Z p Start creating your Strapi application. It might take a minute, please take a coffee bo8
2019-02-25T18:12:43.968279216Z 
2019-02-25T18:12:44.080863697Z Lets configurate the connection to your database:
2019-02-25T18:12:44.080895783Z Database determined by CLI args: mongo
2019-02-25T18:12:44.923803882Z 
2019-02-25T18:12:44.923844215Z b3 Testing database connection...
2019-02-25T18:13:16.217022869Z The app has been connected to the database successfully!
2019-02-25T18:13:16.217067981Z 
2019-02-25T18:13:16.217084409Z p Application generation:
-02-25T18:07:36.859820777Z p Start creating your Strapi application. It might take a minute, please take a coffee bo8
-02-25T18:10:08.093403015Z p Start creating your Strapi application. It might take a minute, please take a coffee bo8
-02-25T18:08:53.525287607Z p Start creating your Strapi application. It might take a minute, please take a coffee bo8
2019-02-25T18:07:36.860329126Z 
2019-02-25T18:10:08.093940772Z 
2019-02-25T18:08:53.525788280Z 
2019-02-25T18:07:36.972719359Z Lets configurate the connection to your database:
-02-25T18:11:24.885955302Z p Start creating your Strapi application. It might take a minute, please take a coffee bo8
2019-02-25T18:08:53.648541612Z Lets configurate the connection to your database:
2019-02-25T18:10:08.204655194Z Lets configurate the connection to your database:
2019-02-25T18:07:36.972753035Z Database determined by CLI args: mongo
2019-02-25T18:11:24.886430547Z 
2019-02-25T18:08:53.648569035Z Database determined by CLI args: mongo
2019-02-25T18:10:08.204684308Z Database determined by CLI args: mongo
2019-02-25T18:07:37.828957888Z 
2019-02-25T18:11:24.999699707Z Lets configurate the connection to your database:
2019-02-25T18:08:54.546807153Z 
2019-02-25T18:07:37.828990378Z b3 Testing database connection...
2019-02-25T18:10:09.069090716Z 
2019-02-25T18:08:54.546841485Z b3 Testing database connection...
2019-02-25T18:11:24.999728765Z Database determined by CLI args: mongo
2019-02-25T18:09:23.512046613Z The app has been connected to the database successfully!
2019-02-25T18:10:09.069123854Z b3 Testing database connection...
2019-02-25T18:08:08.647506619Z The app has been connected to the database successfully!
2019-02-25T18:11:25.875070816Z 
2019-02-25T18:08:08.647551654Z 
2019-02-25T18:09:23.512091558Z 
2019-02-25T18:10:39.682006848Z The app has been connected to the database successfully!
2019-02-25T18:11:25.875104824Z b3 Testing database connection...
2019-02-25T18:08:08.647568718Z p Application generation:
2019-02-25T18:09:23.512107616Z p Application generation:
2019-02-25T18:10:39.682049120Z 
2019-02-25T18:09:52.816975023Z 
2019-02-25T18:11:57.289170556Z The app has been connected to the database successfully!
2019-02-25T18:08:39.727448545Z 
2019-02-25T18:10:39.682060476Z p Application generation:
2019-02-25T18:09:52.817012370Z p Your new application reminder is ready at /usr/src/api/reminder.
2019-02-25T18:11:57.289215483Z 
2019-02-25T18:08:39.727485682Z p Your new application reminder is ready at /usr/src/api/reminder.
2019-02-25T18:11:09.043440486Z 
2019-02-25T18:09:52.817025986Z 
2019-02-25T18:11:57.289227202Z p Application generation:
2019-02-25T18:11:09.044151303Z p Your new application reminder is ready at /usr/src/api/reminder.
2019-02-25T18:09:52.817037011Z b!o8 Change directory:
2019-02-25T18:11:09.044161385Z 
2019-02-25T18:12:29.893111919Z 
2019-02-25T18:08:39.727498876Z 
2019-02-25T18:11:09.044167431Z b!o8 Change directory:
2019-02-25T18:09:52.817050222Z $ cd reminder
2019-02-25T18:12:29.893156390Z p Your new application reminder is ready at /usr/src/api/reminder.
2019-02-25T18:11:09.044173061Z $ cd reminder
2019-02-25T18:09:52.817097653Z 
2019-02-25T18:12:29.893171118Z 
2019-02-25T18:08:39.727561145Z b!o8 Change directory:
2019-02-25T18:11:09.044178460Z 
2019-02-25T18:08:39.727583276Z $ cd reminder
2019-02-25T18:11:09.044183800Z b!o8 Start application:
2019-02-25T18:09:52.817174503Z b!o8 Start application:
2019-02-25T18:08:39.727600472Z 
2019-02-25T18:11:09.044189341Z $ strapi start
2019-02-25T18:09:52.817204575Z $ strapi start
2019-02-25T18:12:29.893185265Z b!o8 Change directory:
2019-02-25T18:08:39.727612205Z b!o8 Start application:
2019-02-25T18:09:56.486314299Z (node:518) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
2019-02-25T18:12:29.893269282Z $ cd reminder
2019-02-25T18:08:39.727676131Z $ strapi start
2019-02-25T18:12:29.893303590Z 
2019-02-25T18:08:40.103238600Z Stopping strapi
2019-02-25T18:11:11.147872297Z Stopping strapi
2019-02-25T18:09:56.584501008Z Stopping strapi
2019-02-25T18:12:29.893376398Z b!o8 Start application:
2019-02-25T18:12:29.893449250Z $ strapi start
2019-02-25T18:12:29.904395594Z ./strapi.sh: wait: line 1: Illegal number: 
2019-02-25T18:12:29.904455708Z Stopping strapi

**Comment by githubsaturn** [comment] 2019-02-25 19:02
Strapi problem is not a CaoRover problem. It's a Strapi problem, particularly it's a RAM issue. 

See https://github.com/caprover/caprover/issues/363


Some people use prebuilt images. See the thread for more details.

**Comment by FloMaetschke** [comment] 2019-02-25 19:18
Do you mean the docker images has not enough memory assigned? Or do you mean the host system?

I have set up a new root server with 48gigs of ram. I would really wonder, if thats not enough. 💃

**Comment by githubsaturn** [comment] 2019-02-25 19:21
That's really bizarre. People who experienced the issue were running on 1GB micro instances. Change your app name and retry. If the issue persists we have to open an issue with Strapi.

Caprover uses official Strapi Docker image.

**Comment by githubsaturn** [comment] 2019-02-25 19:21
Please update here if the issue persists. I'll write up a reproducible case and submit to Strapi.

**Comment by FloMaetschke** [comment] 2019-02-25 19:34
i am right now trying the prebuilt image you suggested. But i agree, official images would be the best.

**Comment by FloMaetschke** [comment] 2019-02-25 19:48
![image](https://user-images.githubusercontent.com/7500948/53363958-02d85b80-393e-11e9-89b3-24c2112de24c.png)

> -02-25T19:44:36.121269934Z p Start creating your Strapi application. It might take a minute, please take a coffee bo8
2019-02-25T19:44:36.121738700Z 
2019-02-25T19:44:36.231416521Z Lets configurate the connection to your database:
2019-02-25T19:44:36.231444739Z Database determined by CLI args: mongo
2019-02-25T19:44:37.115019026Z 
2019-02-25T19:44:37.115055050Z b3 Testing database connection...
-02-25T19:43:19.288675363Z p Start creating your Strapi application. It might take a minute, please take a coffee bo8
2019-02-25T19:43:19.289128148Z 
2019-02-25T19:43:19.401382789Z Lets configurate the connection to your database:
2019-02-25T19:43:19.401414709Z Database determined by CLI args: mongo
2019-02-25T19:43:20.297037832Z 
2019-02-25T19:43:20.297070281Z b3 Testing database connection...
2019-02-25T19:43:52.706661878Z The app has been connected to the database successfully!
2019-02-25T19:43:52.706705135Z 
2019-02-25T19:43:52.706717793Z p Application generation:
2019-02-25T19:44:23.763657740Z 
2019-02-25T19:44:23.763702076Z p Your new application saturn is ready at /usr/src/api/saturn.
2019-02-25T19:44:23.763716757Z 
2019-02-25T19:44:23.763727747Z b!o8 Change directory:
2019-02-25T19:44:23.763740844Z $ cd saturn
2019-02-25T19:44:23.763801280Z 
2019-02-25T19:44:23.763826817Z b!o8 Start application:
2019-02-25T19:44:23.763838053Z $ strapi start
2019-02-25T19:44:23.775407117Z ./strapi.sh: **wait: line 1: Illegal number:** 
2019-02-25T19:44:23.775436067Z Stopping strapi

![image](https://user-images.githubusercontent.com/7500948/53364100-58ad0380-393e-11e9-90da-c1e731f383df.png)

With latest caprover and default settings. I used appname = saturn and password saturn123 :D 


The prebuilt images is runnig, but i also experienced a problem there.
When i try to save an image (media type), which is part of the tutorial of stapi, it did not work.

**Comment by githubsaturn** [comment] 2019-02-28 04:25
@FloMaetschke 

Looked at this again, and this is surely a Strapi bug. I've rebuilt the image and removed HEALTHCHECK from it.

Please try this and let me know if it works.

Go to one-click apps, and select the last option `>>template<<` then copy-paste this:
```
{
    "captainVersion": "1",
    "documentation": "Taken from https://github.com/strapi/strapi-docker/blob/master/docker-compose.yml",
    "dockerCompose": {
        "version": "3.3",
        "services": {
            "$$cap_appname-core": {
                "depends_on": [
                    "$$cap_appname-mongo"
                ],
                "containerHttpPort": "1337",
                "image": "dockersaturn/test-strapi:latest",
                "volumes": [
                    "$$cap_appname-data:/usr/src/api/strapi-app"
                ],
                "restart": "always",
                "environment": {
                    "APP_NAME": "$$cap_appname",
                    "DATABASE_CLIENT": "mongo",
                    "DATABASE_HOST": "srv-captain--$$cap_appname-mongo",
                    "DATABASE_PORT": "27017",
                    "DATABASE_NAME": "strapi",
                    "DATABASE_USERNAME": "root",
                    "DATABASE_PASSWORD": "$$cap_mongo_password",
                    "HOST": "localhost",
                    "DATABASE_AUTHENTICATION_DATABASE": "admin"
                }
            },
            "$$cap_appname-mongo": {
                "image": "mongo:$$cap_mongo_version",
                "notExposeAsWebApp": "true",
                "volumes": [
                    "$$cap_appname-mongo-data:/data/db",
                    "$$cap_appname-mongo-config:/data/configdb"
                ],
                "restart": "always",
                "environment": {
                    "MONGO_INITDB_DATABASE": "strapi",
                    "MONGO_INITDB_ROOT_USERNAME": "root",
                    "MONGO_INITDB_ROOT_PASSWORD": "$$cap_mongo_password"
                }
            }
        },
        "volumes": {
            "db_data": {}
        }
    },
    "instructions": {
        "start": "API creation made simple, secure and fast. The most advanced open-source Content Management Framework to build powerful API with no effort. Read more here: https://strapi.io \n\nNOTE: Hardware requirements: \n2GB minimum RAM required\n1Ghz minimum CPU clock speed",
        "end": "Strapi is deployed and available as $$cap_appname-core \n IMPORTANT!! It takes up to 2 minutes for Strapi to boot up. You will see 502 Error until the startup is finished."
    },
    "variables": [
        {
            "id": "$$cap_mongo_version",
            "label": "MongoDB Version",
            "defaultValue": "4",
            "description": "Checkout their docker page for the valid tags https://hub.docker.com/r/library/mongo/tags/",
            "validRegex": "/^([a-zA-Z0-9])+$/"
        },
        {
            "id": "$$cap_mongo_password",
            "label": "MongoDB password",
            "description": "Only use alphanumeric chars.",
            "validRegex": "/^([a-zA-Z0-9])+$/"
        }
    ]

}
```

**Comment by VikingTristan** [comment] 2019-02-28 20:07
Was having the same issue and your new template worked like a charm for me!

**Comment by githubsaturn** [comment] 2019-02-28 22:54
Yea - then it's definitely a Stapi bug.

@VikingTristan can you please let me know your system spec?
OS? VPS provider? Docker version? RAM? CPU?

**Comment by VikingTristan** [comment] 2019-03-01 21:43
Sure.
It's a "one click" droplet from Digital Ocean: Ubuntu Docker 18.06.1~ce~3 with 2GB RAM, 2vCPUs and 25GB SSD.

**Comment by githubsaturn** [comment] 2019-03-08 05:19
Closing this issue, at it's a Strapi Docker bug. Opened an issue with them, it's up to them to fix this: https://github.com/strapi/strapi-docker/issues/97

**Closed by githubsaturn** 2019-03-08 05:19 UTC
Labels: deployment-issue

**Comment by githubsaturn** [comment] 2019-03-12 02:41
# ---- Update ----

Since strapi doesn't seem to be very active in addressing their issues. I change the default implementation of strapi in CapRover and fixed the problem. No custom template is needed anymore.
