### ISSUE TITLE
[FEATURE] "Copy" application

### ISSUE THREAD

**Issue by Firesphere** [caprover/caprover#1787] opened 2023-06-26 00:53 UTC
**Is your feature request related to a problem? Please describe.**

Every time I add a new application, I usually use the same base configuration for it. Specifically, the Environment Variables.
This means that for every application, I have to copy over the environment variables, or enter them.

**Describe the solution you'd like**

An option to "copy" an app. When I copy the app, and its config/environment variables are pre-filled from the original app, as well as, if possible, mounts if managed by CapRover, (e.g. simply adding `-copy` to the end of the mount name as a default option?) as well as any Nginx customised configuration, if applicable.

This would greatly reduce the time me and my team would spend on setting up a new app.

**Describe alternatives you've considered**

Manually copy the config every time

**Comment by githubsaturn** [comment] 2023-06-26 03:55
Dupe of https://github.com/caprover/caprover/issues/796

**Closed** 2023-06-26 03:55 UTC

**Comment by Firesphere** [comment] 2023-06-26 08:43
Not really a duplicate.

Export (and import), is different from copying. #1540 and #980 would be an actual duplicate (which I missed in my search).

**Comment by githubsaturn** [comment] 2023-06-26 14:07
Same underlying infra. Once one is done the other one is trivial. Also, these issues are linked to the main one.

**Comment by githubsaturn** [comment] 2023-06-26 14:08
Feel free to upvote the main issue. 

Top issues will get addressed first.
