### ISSUE TITLE
Build broken after certificate of git repository was renewed

### ISSUE THREAD

**Issue by FloMaetschke** [caprover/caprover#1213] opened 2021-10-06 15:07 UTC
**What is the problem?**
The automated build from git repository stopped working.
The lets encrypt certificate of my gitea instance (same server) was renewed yesterday by caprover. since then, its no longer building because cloning the repo failed.

I already connected to a bash on the caprover container and reproduced this bevahior at:
`/captain/temp/image_raw/myapp-web`

Itried the mentioned fixes with the checked answer from stackoverflow:
https://stackoverflow.com/questions/35821245/github-server-certificate-verification-failed
But they didn't work. When i disable ssl verification, it works again. But thats no real solution.
My guess is, thats the certificate of the repo is somewhere stored and the old one does no longer match the one on the repo server. (just my guesses)

**Build Log:**
```
------------------------- Wed Oct 06 2021 13:30:44 GMT+0000 (Coordinated Universal Time)
Build started for pdfdoggy-web
Build has failed!
----------------------
Deploy failed!
Error: Cloning into '/captain/temp/image_raw/myapp-web/202/source_files'...
fatal: unable to access 'https://user:pass@git.mysite.com/User/Repo/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

```
**Steps to reproduce the problem:**
Press Force Build button or trigger new build (git push)
Build succeeds.
Renew lets-encrypt certificate on git repo.
Build again.

Output of the following command on your server:

```
root@Ubuntu-1804-bionic-64-minimal ~ # uname -a && lsb_release -a && free -h
Linux Ubuntu-1804-bionic-64-minimal 4.15.0-144-generic #148-Ubuntu SMP Sat May 8 02:33:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
              total        used        free      shared  buff/cache   available
Mem:            47G        6.5G        6.9G         10M         33G         42G
Swap:           23G        2.0M         23G

```

**Comment by FloMaetschke** [comment] 2021-10-07 00:15
further investigations:

other caprover instance has the same error on my gitea repo.
other repos do work correctly.
my guess, it has something todo with letsencrypt and the caprover container.

Chrome says, my gitea's repo certificate is fine, its letsencrypt. everything is ok

**Comment by githubsaturn** [comment] 2021-10-09 22:02
Duplicate of https://github.com/caprover/caprover/issues/1215

**Closed by githubsaturn** 2021-10-09 22:02 UTC
Labels: deployment-issue
