### ISSUE TITLE
[Deployment Issue] Deploying custom one-click app

### ISSUE THREAD

**Issue by khromov** [caprover/caprover#575] opened 2020-01-04 03:57 UTC
> What is the problem?

I have written a modified version of the [wordpress.json file from the One-click repo](https://github.com/caprover/one-click-apps/blob/master/public/v2/apps/wordpress.json) that also includes a Memcached image. 

Now I'm looking for a way to add it to the list of  "One-click apps" on my CapRover installation. How do I do this without submitting it to the https://github.com/caprover/one-click-apps/ repo?

The main reason I can't just use a Dockerfile or `captain-definition` is that I need to create multiple services and also need to set up volumes and listening ports for each service, which is impossible from Dockerfile or `captain-definition`.

It would be really great if we could add our new one-click app definitions by putting a JSON file in some configuration folder CapRover manages, or if we could supply a completely different repo from where to fetch One-Click apps.

Related issue:
https://github.com/caprover/caprover/issues/416

Tangentially related issue:
https://github.com/caprover/caprover/issues/353

**Comment by githubsaturn** [comment] 2020-01-04 17:50
As you mentioned, this is a duplicate of #416

We'll implement the custom one-click app repo soon. In the meantime, the alternative is to simply copy and paste your template json into the TEMPLATE one click app:
![image](https://user-images.githubusercontent.com/10582082/71769522-9e3c4480-2ef0-11ea-9f09-fcec751c91d9.png)

Alternatively, in the meantime, you can "bookmark" the page where you enter values for your one-click app. This will work too as the entire json is embedded in the URL.

**Closed** 2020-01-04 17:50 UTC
Labels: deployment-issue
