### ISSUE TITLE
[FEATURE] Support duplicating a container / creating a template from a container

### ISSUE THREAD

**Issue by R3D347HR4Y** [caprover/caprover#1540] opened 2022-10-20 08:27 UTC
**Is your feature request related to a problem? Please describe.**
Having to set up multiple containers for staging, production, different branches is a pain, as we have to create a new container, add the image, the environnement variables which often times are the same and set all types of settings

**Describe the solution you'd like**
A button 'Duplicate app' that creates another app with the exact same properties except domain name and container name (which you enter after clicking the button)
Also a checkbox to choose weather to use the same storage as the app you're cloning or to generate new volumes.

**Describe alternatives you've considered**
Messing with config files manually, not using caprover

**BIG UPSIDE**
This simple feature has the potential to attract big teams to use Caprover and sponsor it

**Comment by githubsaturn** [comment] 2022-10-21 04:45
Dupe of https://github.com/caprover/caprover/issues/796

**Closed by githubsaturn** 2022-10-21 04:45 UTC
