### ISSUE TITLE
Backup captainduckduck apps

### ISSUE THREAD

**Issue by danielivert** [caprover/caprover#187] opened 2018-02-16 10:01 UTC
I am thinking on a feature to have a backup of all the apps with the settings they need to work. Example:
- Domains (Probably auto-generate the SSL again?)
- Environmental Variables
- Persistent Directories
- Port mapping
- Git settings

This would be very useful if something goes wrong with the server, or if you need to migrate to another server then it would save a lot of time, you will only need to push the apps to captainduckduck and they should be up and running.

**Comment by DougKrioK** [comment] 2018-02-16 10:42
great!

**Comment by githubsaturn** [comment] 2018-02-19 00:32
Backup of CaptainDuckDuck configurations and even SSL certificates are doable. But Docker volume backup is a totally different beast. We won't be able to create a one-fits-all tool for Docker Volumes. Consider a case where there is a persistent directory on a secondary node. CaptainDuckDuck has no access to that directory - at least with current Docker functionalities. So backing up Persistent Directories has to be a customized solution. There are many projects that created a helper for this purpose, but none of them is a simple `create backup` and `restore backup` kind of thing. So, to put it in a nut-shell, you can expect this in the future:

- Domains (Probably auto-generate the SSL again?) :white_check_mark: 
- Environmental Variables :white_check_mark: 
- Mapping of Persistent Directories :white_check_mark: 
- Persistent Directories :x: might be able to create some sort of "helpers", but, we won't be able to create a ready to go solution for this one.
- Port mapping :white_check_mark: 
- Git settings :white_check_mark:

**Comment by drmrbrewer** [comment] 2018-06-15 20:12
I'd really love to see this as a built-in function... hopefully one day!

But with your manual solution, when you want to migrate the captain configuration to the new server, would it just be a case of replacing the content of the `/captain` folder on the new server with that from the old server?  Of course, having scaled captain to 0 beforehand, and scaling back to 1 after.

**Comment by githubsaturn** [comment] 2018-06-16 03:34
> I'd really love to see this as a built-in function... hopefully one day!

This feature is my favorite and will be useful. But it's not a quick task at all. Once I get some free time, I'll work on this.

> But with your manual solution, when you want to migrate the captain configuration to the new server, would it just be a case of replacing the content of the /captain folder on the new server with that from the old server? Of course, having scaled captain to 0 beforehand, and scaling back to 1 after.

There is some more work to be done:
1- Remove the `captainRegistryAuthSecretVer` field from `/captain/config.conf` if it exists. And update your docker registry at the last step once everything is up and running again.
2- Remove the `hashedPassword`, it defaults to `captain42` and reset your password once the new instance is up and running.
3- redeploy all your apps (`captainduckduck deploy`)


Step 1 and 2 are due to Captain's secret salt which is encrypted and is part of docker swarm. These two steps will be gone once we take Captain salt as a config param. Step 3, however, will never be done automatically as your images will be gone. The only way to fix that would be to use another server (whether 3rd party or self hosted for Docker registry).


- Copy the salt value and store it somewhere safe:
```
docker exec -t $(docker ps --filter name=captain-captain -q) bash -c "cat /run/secrets/captain-salt && echo '' "
```
- Copy the secret to the new server:

**Comment by drmrbrewer** [comment] 2018-06-17 09:15
In step 1, what do you mean by "update your docker registry"?  All I would normally do when setting up captain is to enable the self-hosted registry, and then subsequent deploys will automatically interact with the registry.

**Comment by githubsaturn** [comment] 2018-06-19 15:15
I meant setting up when i said "update your docker registry". So exactly what you currently do. 


And yes. You can remove docker registry directory before back up to ensure a clean start.

**Comment by drmrbrewer** [comment] 2018-06-26 20:57
Trying to get this to work.  I have backed up the `/captain` folder on the existing server (minus the registry) and restored it on the new server.  I restart captain on the new server.  But I cannot access captain via `http://[IP_address_of_new_server]:3000/` (just redirects to https equivalent and says "This site can’t be reached".  And doing `captainduckduck serversetup` from the IDE, and entering the IP address of the new server, gives:

	Something bad happened. Cannot connect to "http://xxx.yy.zz.aa:3000/api/v1/login"
	{
	  "statusCode": 302,
	  "body": "Found. Redirecting to https://xxx.yy.zz.aa:3000/api/v1/login",
	  "headers": {
		"x-powered-by": "Express",
		"location": "https://xxx.yy.zz.aa:3000/api/v1/login",
		"vary": "Accept",
		"content-type": "text/plain; charset=utf-8",
		"content-length": "60",
		"date": "Tue, 26 Jun 2018 20:52:44 GMT",
		"connection": "close"
	  },
	  "request": {
		"uri": {
		  "protocol": "http:",
		  "slashes": true,
		  "auth": null,
		  "host": "xxx.yy.zz.aa:3000",
		  "port": "3000",
		  "hostname": "xxx.yy.zz.aa",
		  "hash": null,
		  "search": null,
		  "query": null,
		  "pathname": "/api/v1/login",
		  "path": "/api/v1/login",
		  "href": "http://xxx.yy.zz.aa:3000/api/v1/login"
		},
		"method": "POST",
		"headers": {
		  "x-namespace": "captain",
		  "x-captain-auth": null,
		  "content-type": "application/x-www-form-urlencoded",
		  "content-length": 18
		}
	  }
	}

**Comment by githubsaturn** [comment] 2018-06-27 06:42
That's the expected behavior. You are restoring the previous state of the server which was forcefully redirecting HTTP traffic to HTTPS. You won't be able to connect to it on HTTP at all. Let's say previously you connected to your server via `captain.something.com`, you need to change your DNS such that `*.something.com` points to the new server. Then simply going to `captain.something.com` should take you to the dashboard. Also, instead of `captainduckduck serversetup`, you should use `captain login` as your server is already set up.

**Comment by drmrbrewer** [comment] 2018-06-27 07:38
Sure, makes sense.  Now I can access captain on the new server.  Having previously removed the lines containing `captainRegistryAuthSecretVer` and `hashedPassword`, I log in with the default password.  But when I browse to the Apps tab on the new captain console (hoping to see all the same apps I have on the existing server), I get "Error: Token corrupted", with the following in captain logs:

	2018-06-27T07:34:27.261333530Z June 27th 2018, 7:34:27.260 am    JsonWebTokenError: invalid signature
	2018-06-27T07:34:27.266584332Z June 27th 2018, 7:34:27.265 am    Error: Token corrupted
	2018-06-27T07:34:27.266595758Z Error: Token corrupted
	2018-06-27T07:34:27.266599619Z     at Object.createError (/usr/src/app/src/api/ApiStatusCodes.js:5:21)
	2018-06-27T07:34:27.266603342Z     at /usr/src/app/src/user/Authenticator.js:192:43
	2018-06-27T07:34:27.266606933Z     at Object.module.exports [as verify] (/usr/src/app/node_modules/jsonwebtoken/verify.js:102:12)
	2018-06-27T07:34:27.266610530Z     at /usr/src/app/src/user/Authenticator.js:189:17
	2018-06-27T07:34:27.266614056Z     at new Promise (<anonymous>)
	2018-06-27T07:34:27.266617542Z     at Authenticator.decodeGenericToken (/usr/src/app/src/user/Authenticator.js:187:16)
	2018-06-27T07:34:27.266621116Z     at Authenticator.decodeAppPushWebhookDatastore (/usr/src/app/src/user/Authenticator.js:149:21)
	2018-06-27T07:34:27.266624539Z     at /usr/src/app/src/routes/AppDefinitionRouter.js:122:30
	2018-06-27T07:34:27.266627885Z     at Array.forEach (<anonymous>)
	2018-06-27T07:34:27.266631313Z     at /usr/src/app/src/routes/AppDefinitionRouter.js:112:31
	2018-06-27T07:34:27.266640083Z GET /api/v1/user/appDefinitions/ 304 12.880 ms - -

I have checked in `/captain/config.conf` and it appears to contain everything that is present on the existing server, i.e. all the apps and their configurations.

**Comment by githubsaturn** [comment] 2018-06-28 00:31
> Sure, makes sense. Now I can access captain on the new server. Having previously removed the lines containing captainRegistryAuthSecretVer and hashedPassword, I log in with the default password. But when I browse to the Apps tab on the new captain console (hoping to see all the same apps I have on the existing server), I get "Error: Token corrupted", with the following in captain logs:

I missed one more thing that's encrypted... You have to remove the **content of** `appPushWebhook` in all your apps. i.e. you should have: ` "appPushWebhook" : {}` 

In hindsight it would have been more appropriate to encrypt the entire file or even leave everything unencrypted.


> P.S. if the self-hosted docker registry folder is included in what is backed up and restored to the new server, would it be the case that all of the apps/services that were running on the previous server would load and run on the new server when captain is started, even without having to re-deploy all the apps again? That would make spinning up a new server even more easy! That would be amazing! Yes, there is still the data in the persistent folders that needs to be restored, but again that could be restored from a separate backup file.

Not currently. But in the future, this is surely something we can do.

**Comment by drmrbrewer** [comment] 2018-06-28 07:34
> You have to remove the content of `appPushWebhook`

Ah OK that's a shame, since the entire captain configuration will not be migrated across... nearly but not quite!

> In hindsight it would have been more appropriate to encrypt the entire file or even leave everything unencrypted

If the *whole* file is encrypted then this would presumably prevent meaningful user access to the file, such as what I'm doing now... I'm backing up the captain config file regularly (with crontab) so that I always have a recent config available and ready to go (e.g. if server dies and I cannot even manually create a new config backup).  Then when spinning up a new server I have an init script which installs captain and loads the saved captain config (making any edits as necessary to remove lines as stated above).  I'm trying to automate the process as far as possible (hence it's a shame having to make any manual edits like adding back the missing webhook info).  

Hopefully this will still be possible with any future plans you have in mind.  Maybe it's preferable to leave the entire file unencrypted, for maximum flexibility?  There may be other stuff in there that is sensitive, but which isn't yet encrypted, so best just to leave it all unencrypted since the file should in theory be inaccessible to third parties anyway?

**Comment by drmrbrewer** [comment] 2018-09-17 19:40
I've come back to this after a bit of a break, trying to get it working fully.  I've got so far as automatically restoring my captain config from a remote backup, and I can log onto captain console and all the app settings are there.

I'm a bit confused about what is required in particular to get apps with persistent storage up and running again (with the persistent storage folders created).  One of my apps has the following settings, immediately after restoring the settings from the original captain server:

![image](https://user-images.githubusercontent.com/9009792/45645850-a97c1e80-bab9-11e8-8957-0a9a0476bd76.png)

Part of the captain-definition file that deploys this app also needs to put some stuff into one of the persistent folders, but the build is failing at that point because the folder doesn't exist.

**Comment by githubsaturn** [comment] 2018-09-18 05:58
I am not sure which of the following two scenarios you meant by saying:
> but the build is failing at that point because the folder doesn't exist

Scenario 1)
You don't need to put any previously backed up data in those directories. They just need to exist for the build to run. If that's the case, you just need to create the volumes:
```
docker volume create captain--cloud9-ssh
```
And the same for the other two volumes. Pay attention to the prefix `captain--`.

Scenario 2)
You have backed up the volume data and this data needs to be there before the build starts. Then you need to do what I said in Scenario 1, and then copy it at the location where the volume is mounted. To get the location of a volume:

```
docker volume inspect captain--cloud9-ssh --format '{{.Mountpoint}}'
```

**Comment by drmrbrewer** [comment] 2018-09-18 09:37
That's really helpful.  Based on my new understanding I moved some of the stuff I was doing in the `captain-definition` for the app and into the `cloud-init` script that I use to spin up the new server, in order to ensure that all the persistent volumes for the app are re-populated from backup.  So I'm using scenario 1 and 2 in effect.  Thanks.

**Comment by drmrbrewer** [comment] 2018-09-19 08:58
Note that in the screenshot I posted just above, the `Node ID` for the volumes is preset, after restoring the captain config from backup, and will of course no longer be valid for the new server.  Is this something that has to be changed manually, or will it be set automatically when the app is deployed for the first time to the new captain server?  Perhaps I could remove any hardcoded `Node ID` in the captain config when restoring it, so that it starts out `undefined` rather than an id that isn't valid at all?

**Comment by githubsaturn** [comment] 2018-09-19 16:08
Has to be manually set. Run `docker node ls` to get the node ID.

**Comment by drmrbrewer** [comment] 2018-09-23 07:35
Thanks.  I'm doing it manually, in an automated fashion, as part of a start-up script... grabbing the node ID with `docker node ls -qf role=manager` and doing a search/replace on the config file.

Couple more things on the way to having a near fully-automated process... once everything has been restored from the previous state, is it possible to enable the self-hosted registry again without having to log into the new console and pressing the button?  And what about enabling NetData... possible to do this in the start-up script without pressing buttons in the console?  The console thinks that NetData is enabled, so I have to Stop it then Start it again... of course it's not much hassle when I now have most of it automated but it would be nice to go the whole way!

And of course I have to add the github webhook back manually because there is no way of automating that.

**Comment by drmrbrewer** [comment] 2018-09-23 18:15
It doesn't spin up the registry when I scale captain down to 0 (`docker service scale captain-captain=0`) and then back up to 1 (`docker service scale captain-captain=1`)... is that different to doing `docker update captain-captain --force`?

**Comment by drmrbrewer** [comment] 2018-09-23 18:29
After scaling back to 1 (not sure about before), I do see:

    1b798ub4v30y        captain-registry         replicated          1/1                 registry:2                              *:996->5000/tcp

But in the console I see:

![image](https://user-images.githubusercontent.com/9009792/45931509-e7b88880-bf66-11e8-8af6-fd53cd2c2239.png)

i.e. button is there to press (not greyed out) and it doesn't seem that deploys are being pushed to the registry.

**Comment by githubsaturn** [comment] 2018-09-23 18:56
That makes much more sense. It's what I was expecting. Captain uses docker swarm secrets to save the password for docker registry. Docker secrets are not part of Captain config. So yes, this is the expected behavior and has to be dealt with manually until backup is supported by Captain.

**Comment by drmrbrewer** [comment] 2018-09-24 11:21
For an app that I deploy via webhook (method 3), I have to remove the webhook info as per: https://github.com/githubsaturn/captainduckduck/issues/187#issuecomment-400872764.  For this app, when I go into the captain console (with restored settings), and go to the app, and enter the repo details in order to generate a new webhook, then hit Update and Save, a red ERROR message is issued.  But when I click off the app page, then go back into it, the webhook is there anyway, and sure enough it works when I put it in github... starts deploying.  I know what I'm doing here (restoring captain settings) is non-standard, but maybe there is something you can do to prevent the ERROR message showing, because in fact there doesn't seem to be any error?

**Comment by githubsaturn** [comment] 2018-09-24 16:03
There might be some errors happening. Can you get CaptainDuckDuck's logs when doing this?

**Comment by drmrbrewer** [comment] 2018-09-24 20:35
OK it makes some sense I guess, because in order to generate the webhook you need to Save and Update the app, but since there is no no docker service for the app yet, it results in an error.  It would seem better to have a separate button in the webhook section to generate the webhook without having to Save and Update.

Here are the captain logs when doing a Save and Update:

	GET /api/v1/user/appData/myapp 304 3.770 ms - -
	September 24th 2018, 8:30:51.148 pm    Updating app started: myapp
	September 24th 2018, 8:30:51.208 pm    Error: (HTTP code 404) no such service - service srv-captain--myapp not found 
	Error: (HTTP code 404) no such service - service srv-captain--myapp not found 
		at /usr/src/app/node_modules/docker-modem/lib/modem.js:254:17
		at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:284:7)
		at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:253:5)
		at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:229:14)
		at emitNone (events.js:110:20)
		at IncomingMessage.emit (events.js:207:7)
		at endReadableNT (_stream_readable.js:1057:12)
		at _combinedTickCallback (internal/process/next_tick.js:138:11)
		at process._tickCallback (internal/process/next_tick.js:180:9)
	POST /api/v1/user/appDefinitions/update 500 67.334 ms - 21
	GET /api/v1/user/appData/myapp 304 3.219 ms - -

**Comment by luisfavila** [comment] 2018-11-27 06:14
I've been reading your discussion since I'd like to move captain to another server and something crossed my mind:
@githubsaturn you've mentioned in #162 that by sharing the `/captain` folder with master nodes one could theoretically spin captain up in another master node when the leader dies. So, would it be any different if we were to spin captain from backup files on a master node?

**Comment by drmrbrewer** [comment] 2019-01-19 09:15
@githubsaturn will the release of `CapRover` affect the fundamentals of what I'm doing here, i.e. backing up `/captain/config.conf` and using that backup when spinning up a new `captain` (or `caprover`) server, making a few "manual" edits to the conf file (such as [this](https://github.com/caprover/caprover/issues/187#issuecomment-397783357)) before doing so?  I've got a nice automated backup-and-restore method going so I need to check if this is going to be affected when the time comes to upgrade to `CapRover 1.0.0`.  Thanks!

**Comment by githubsaturn** [comment] 2019-01-19 17:07
@drmrbrewer 

Yes, it will affect your process, but not drastically. The location of directories have changed. But in a good way! All directories and files that you want to backup, are in `/captain/data/`. You still have to remove the encrypted content from the config file, which now located at `/captain/data/config-captain.json` :
- hashed password
- appWebHooks for github deployments
- registry related content.


Also depending on your use case, you may want to remove the registry directory before creating the backup as it consumes so much space. The registry directory is now located at `/captain/data/registry`

All these changes were made to make automatic creation of backups possible. The backup is still not implemented as part of CapRover core. However, with these new changes, it is now possible to bring that feature to our road map.

**Comment by drmrbrewer** [comment] 2019-01-19 21:39
Great, thanks @githubsaturn ... a few name and path changes I can cope with :)

**Closed** 2019-03-08 05:20 UTC
Labels: enhancement

**Comment by drmrbrewer** [comment] 2019-09-24 13:40
@githubsaturn at present I'm backing up my captain folder with the following:

    tar --exclude='/captain/generated' --exclude='/captain/temp' --exclude='/captain/data/registry/docker/registry/v2' -cvzf - /captain

even with the excluded folders, the output file is around 30 MB in size.  Not catastrophic, but still quite big.  I'm wondering whether any other folders can safely be excluded from the archive, whilst still leaving an archive that can be used to restore the complete caprover setup on a new server (minus any generated stuff that can be re-generated).

**Comment by drmrbrewer** [comment] 2020-12-10 08:51
@githubsaturn any thoughts on reducing backup file size (see post just above)?  I'm still using the same backup command, and the compressed backup file is now up to 103 MB in size, with 54979 `.pem` files in `/captain/data/letencrypt/etc/keys`.  Any way to keep this backup file from just growing ever larger over time?

**Comment by githubsaturn** [comment] 2020-12-10 12:24
Unfortunately let's encrypt client (certbot) doesn't have a "prune" command. Feel free to open a new issue to run cron-like clean up operation on certs.

**Comment by drmrbrewer** [comment] 2020-12-10 12:27
OK... does take up a lot of space:

    # du -hs /captain/data/letencrypt/etc/keys
    218M    /captain/data/letencrypt/etc/keys

**Comment by drmrbrewer** [comment] 2023-08-28 09:50
@githubsaturn I'm fully supportive of the introduction of a pro subscription option as introduced by [version 1.11.0](https://github.com/caprover/caprover/releases/tag/v1.11.0), but before subscribing and enabling 2FA, I need to check how this (and any other new features) might impact the backup/restore process set out in this issue.  

In particular, after spinning up a new server, installing caprover, and fetching/restoring the saved caprover config file, I do various housekeeping tasks using `caprover api`, including setting the correct node id for the apps with persistent volumes, setting up the local registry, re-starting NetData... and also changing the password from the default.

For changing the password, I use:

`caprover api --configFile "${CAPROVER_CONFIG_FILE}"`

where the content of `CAPROVER_CONFIG_FILE` is set to:

```
{
    "caproverName": "${CAPROVER_NAME}",
    "caproverUrl": "${CAPROVER_URL}",
    "caproverPassword": "${CAPROVER_DEFAULT_PWD}",
    "path": "/user/changepassword",
    "method": "POST",
    "data": {
        "oldPassword": "${CAPROVER_DEFAULT_PWD}",
        "newPassword": "${CAPROVER_PWD}"
    }
}
```

Thereafter, logging in (and deploying apps) to the new CapRover instance works fine using the specified password.  

But will this still work with 2FA enabled?

**Comment by githubsaturn** [comment] 2023-08-28 13:45
Changing password will work fine. But for logging in, you have to pass a new value (otpToken):

```bash
fetch("https://captain.domain.com/api/v2/login", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "content-type": "application/json",
    "x-namespace": "captain"
  },
  "body": "{\"password\":\"asdf\",\"otpToken\":\"123456\"}",
  "method": "POST"
});
```

**Comment by githubsaturn** [comment] 2023-08-28 13:46
For deployments, as long as you have a valid auth token things will work fine, but if you need to re-login, then no. You'll have to pass in your 2FA.

See here for more details on 2FA enabled deployments: https://github.com/caprover/caprover/issues/1854

**Comment by drmrbrewer** [comment] 2023-08-28 15:27
@githubsaturn will the 2FA setup survive the backup/restore, so it's the same `otpToken` as before, or would this need to be set up again for the new server (even with `/captain/data/config-captain.json` restored from previous server)?
